from __future__ import annotations

import json
import hashlib
from dataclasses import dataclass
from pathlib import Path


@dataclass
class SyncResult:
    ok: bool
    reason_codes: list[str]
    authority_hash: str


def _normalize(payload: dict) -> str:
    return json.dumps(payload, sort_keys=True, separators=(",", ":"))


def _roadmap_index(payload: dict) -> dict[str, dict]:
    return {row["batch_id"]: row for row in payload.get("batches", [])}


def _render_markdown(authority: dict) -> str:
    lines = [
        "# Spectrum Systems — System Roadmap",
        "",
        "<!-- Generated by RMP authority sync; do not hand-edit tables. -->",
        "",
        "**Authority status:** ACTIVE ROADMAP AUTHORITY",
        "",
        "- System source of truth (machine-readable): `contracts/examples/system_roadmap.json`",
        "",
        "## Governed Batch Table",
        "",
        "| batch_id | acronym | title | status | depends_on | hard_gate |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for batch in authority.get("batches", []):
        deps = ", ".join(batch.get("depends_on", [])) if batch.get("depends_on") else "—"
        lines.append(
            f"| {batch.get('batch_id', 'UNKNOWN')} | {batch.get('acronym', '')} | {batch.get('title', '')} | "
            f"{batch.get('status', 'not_started')} | {deps} | {str(batch.get('hard_gate', False)).lower()} |"
        )
    lines.append("")
    return "\n".join(lines)


def sync_authority(
    authority_path: Path,
    markdown_path: Path,
    *,
    apply_fixes: bool = False,
) -> SyncResult:
    authority = json.loads(authority_path.read_text(encoding="utf-8"))
    markdown = markdown_path.read_text(encoding="utf-8")

    reasons: list[str] = []
    authority_index = _roadmap_index(authority)
    for batch_id, row in authority_index.items():
        if batch_id not in markdown:
            reasons.append(f"missing_markdown_entry:{batch_id}")
        if row.get("status") == "implemented":
            reasons.append(f"invalid_status_token:{batch_id}")

    if "| batch_id | acronym | title | status | depends_on |" not in markdown:
        reasons.append("missing_markdown_table")

    ok = not reasons
    if apply_fixes and reasons:
        markdown_path.write_text(_render_markdown(authority), encoding="utf-8")
        reasons = []
        ok = True

    digest = hashlib.sha256(_normalize(authority).encode("utf-8")).hexdigest()
    return SyncResult(ok=ok, reason_codes=sorted(set(reasons)), authority_hash=digest)
