export type PanelFieldProvenance = {
  panel_id: string
  artifact: string
  fields: string[]
  transformation_path?: string[]
  uncertainty?: string
}

export const PANEL_FIELD_PROVENANCE_MAP: PanelFieldProvenance[] = [
  { panel_id: 'trust_posture', artifact: 'dashboard_freshness_status.json', fields: ['status', 'freshness_window_hours', 'snapshot_last_refreshed_time', 'trace_id'] },
  { panel_id: 'trust_posture', artifact: 'dashboard_publication_sync_audit.json', fields: ['publication_state', 'required_artifact_count', 'records'] },
  { panel_id: 'causal_chain', artifact: 'judgment_application_artifact.json', fields: ['decision_id', 'judgment_ids'], transformation_path: ['judgment_application_artifact.decision_id -> causal_chain.judgment_node'] },
  { panel_id: 'causal_chain', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes', 'timestamp'], transformation_path: ['publication_attempt_record.decision -> causal_chain.control_node'] },
  { panel_id: 'causal_chain', artifact: 'hard_gate_status_record.json', fields: ['readiness_status', 'pass_fail'], transformation_path: ['hard_gate_status_record.readiness_status -> causal_chain.eval_node'] },
  { panel_id: 'causal_chain', artifact: 'serial_bundle_validator_result.json', fields: ['pass'], transformation_path: ['serial_bundle_validator_result.pass -> causal_chain.outcome_node'] },
  { panel_id: 'decision_trace', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes', 'trace_id'] },
  { panel_id: 'decision_trace', artifact: 'judgment_application_artifact.json', fields: ['decision_id', 'judgment_ids'] },
  { panel_id: 'decision_trace', artifact: 'hard_gate_status_record.json', fields: ['gate_name', 'readiness_status'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'current_bottleneck_record.json', fields: ['bottleneck_name', 'impacted_layers'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'current_run_state_record.json', fields: ['current_run_status', 'repair_loop_count'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'hard_gate_status_record.json', fields: ['readiness_status'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'judgment_application_artifact.json', fields: ['decision_id'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'serial_bundle_validator_result.json', fields: ['pass'] },
  { panel_id: 'evidence_strength', artifact: 'dashboard_publication_sync_audit.json', fields: ['records', 'required_artifact_count'] },
  { panel_id: 'evidence_strength', artifact: 'dashboard_freshness_status.json', fields: ['status', 'snapshot_age_hours'] },
  { panel_id: 'evidence_strength', artifact: 'serial_bundle_validator_result.json', fields: ['pass'] },
  { panel_id: 'evidence_strength', artifact: 'dashboard_public_contract_coverage.json', fields: ['covered_artifacts'], uncertainty: 'Coverage artifact does not include uncovered severity by slice; panel computes count only.' },
  { panel_id: 'control_decisions', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes', 'timestamp', 'trace_id'] },
  { panel_id: 'control_decisions', artifact: 'hard_gate_status_record.json', fields: ['gate_name', 'readiness_status', 'pass_fail'] },
  { panel_id: 'judgment_records', artifact: 'judgment_application_artifact.json', fields: ['decision_id', 'judgment_ids', 'consumed_by_control'] },
  { panel_id: 'override_lifecycle', artifact: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', fields: ['overrides.override_id', 'overrides.reason', 'overrides.operator_action'] },
  { panel_id: 'replay_certification', artifact: 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', fields: ['scenario_ids', 'scenario_basis'] },
  { panel_id: 'replay_certification', artifact: 'serial_bundle_validator_result.json', fields: ['pass', 'pass_through_umbrellas', 'empty_batches'] },
  { panel_id: 'replay_certification', artifact: 'governed_promotion_discipline_gate.json', fields: ['promotion_decision', 'allowed_decisions', 'fail_closed'] },
  { panel_id: 'weighted_coverage', artifact: 'dashboard_public_contract_coverage.json', fields: ['covered_artifacts'] },
  { panel_id: 'weighted_coverage', artifact: 'dashboard_publication_manifest.json', fields: ['required_files'] },
  { panel_id: 'trend_control_charts', artifact: 'dashboard_freshness_status.json', fields: ['snapshot_age_hours', 'freshness_window_hours'], uncertainty: 'No historical series artifact published; single-sample chart only.' },
  { panel_id: 'trend_control_charts', artifact: 'publication_attempt_record.json', fields: ['decision'] },
  { panel_id: 'reconciliation', artifact: 'dashboard_freshness_status.json', fields: ['status'] },
  { panel_id: 'reconciliation', artifact: 'publication_attempt_record.json', fields: ['decision'] },
  { panel_id: 'postmortem_outage', artifact: 'refresh_run_record.json', fields: ['outcome', 'failure_class', 'trace_id'] },
  { panel_id: 'tamper_evident_ledger', artifact: 'dashboard_publication_sync_audit.json', fields: ['records.sha256', 'records.artifact'] },
  { panel_id: 'tamper_evident_ledger', artifact: 'serial_bundle_validator_result.json', fields: ['pass'] },
  { panel_id: 'maintain_drift', artifact: 'dashboard_public_contract_coverage.json', fields: ['covered_artifacts'] },
  { panel_id: 'maintain_drift', artifact: 'dashboard_publication_manifest.json', fields: ['required_files'] },
  { panel_id: 'scenario_simulator', artifact: 'rq_next_24_01__umbrella_3__nx_17_failure_hotspot_simulation_pack.json', fields: ['scenario_ids', 'hypotheses'] },
  { panel_id: 'mobile_semantics', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes'] },
  { panel_id: 'policy_visibility', artifact: 'hard_gate_status_record.json', fields: ['gate_name', 'readiness_status', 'required_evidence'] },
  { panel_id: 'policy_visibility', artifact: 'governed_promotion_discipline_gate.json', fields: ['promotion_decision', 'allowed_decisions', 'fail_closed'] },
  { panel_id: 'audit_trail', artifact: 'publication_attempt_record.json', fields: ['publish_attempt_id', 'decision', 'trace_id', 'timestamp'] },
  { panel_id: 'audit_trail', artifact: 'judgment_application_artifact.json', fields: ['decision_id', 'judgment_ids'] },
  { panel_id: 'audit_trail', artifact: 'refresh_run_record.json', fields: ['refresh_run_id', 'run_id', 'trace_id', 'outcome'] },
  { panel_id: 'action_surface', artifact: 'refresh_run_record.json', fields: ['refresh_run_id', 'trigger_mode'] },
  { panel_id: 'action_surface', artifact: 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', fields: ['scenario_ids'] },
  { panel_id: 'action_surface', artifact: 'recommendation_review_surface.json', fields: ['pending_reviews', 'checkpoint_count'], uncertainty: 'Review artifact shape is partially optional; missing keys are blocked.' },
  { panel_id: 'review_queue_surface', artifact: 'recommendation_review_surface.json', fields: ['pending_reviews', 'checkpoint_count', 'status'] },
  { panel_id: 'review_queue_surface', artifact: 'hard_gate_status_record.json', fields: ['readiness_status'] },
  { panel_id: 'misinterpretation_guard', artifact: 'dashboard_freshness_status.json', fields: ['status', 'snapshot_age_hours'] },
  { panel_id: 'misinterpretation_guard', artifact: 'serial_bundle_validator_result.json', fields: ['pass'] },
  { panel_id: 'misinterpretation_guard', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes'] },
  { panel_id: 'operator_coordination_layer', artifact: 'dashboard_publication_manifest.json', fields: ['required_files', 'publication_state'] },
  { panel_id: 'decision_change_conditions', artifact: 'judgment_application_artifact.json', fields: ['change_conditions'] },
  { panel_id: 'evidence_gap_hotspots', artifact: 'readiness_to_expand_validator.json', fields: ['missing_evidence_refs', 'affected_claims', 'materiality_basis', 'certification_relevant'] },
  { panel_id: 'override_hotspots', artifact: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', fields: ['overrides.override_id', 'overrides.operator_action', 'overrides.reason'] },
  { panel_id: 'trust_posture_timeline', artifact: 'operator_trust_closeout_artifact.json', fields: ['snapshots.timestamp', 'snapshots.freshness', 'snapshots.provenance_completeness', 'snapshots.validation_coverage', 'snapshots.replay_status', 'snapshots.trace_completeness'] },
  { panel_id: 'judge_disagreement', artifact: 'cycle_comparator_03_05.json', fields: ['disagreements.dimension', 'disagreements.status', 'disagreements.linked_review_id'] },
  { panel_id: 'policy_regression', artifact: 'cycle_comparator_03_05.json', fields: ['policy_drift', 'candidate_regressions', 'changed_outcomes'] },
  { panel_id: 'capability_readiness', artifact: 'readiness_to_expand_validator.json', fields: ['readiness_state', 'evidence_basis', 'confidence', 'missing_data_indicators'] },
  { panel_id: 'route_efficiency', artifact: 'operator_trust_closeout_artifact.json', fields: ['route_efficiency.route', 'route_efficiency.quality', 'route_efficiency.cost', 'route_efficiency.latency', 'route_efficiency.uncertainty'] },
  { panel_id: 'failure_derived_eval', artifact: 'next_action_outcome_record.json', fields: ['outcomes.failure_id', 'outcomes.eval_case_id', 'outcomes.operationalized'] },
  { panel_id: 'correction_patterns', artifact: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', fields: ['overrides.reason', 'overrides.operator_action', 'overrides.captured_as_learning_signal'] },
  { panel_id: 'review_outcomes', artifact: 'recommendation_review_surface.json', fields: ['pending_reviews.review_id', 'pending_reviews.status', 'pending_reviews.checkpoint'] },
  { panel_id: 'escalation_triggers', artifact: 'hard_gate_status_record.json', fields: ['warn_threshold', 'freeze_threshold', 'block_threshold', 'current_risk_score'] },
  { panel_id: 'escalation_triggers', artifact: 'publication_attempt_record.json', fields: ['decision'], uncertainty: 'Threshold proximity is advisory and separate from decision artifact.' },
  { panel_id: 'cross_run_intelligence', artifact: 'cycle_comparator_03_05.json', fields: ['convergence', 'instability', 'recurring_disagreement', 'repeating_failure_patterns'] },
  { panel_id: 'high_risk_claim_board', artifact: 'readiness_to_expand_validator.json', fields: ['missing_evidence_refs', 'affected_claims'], uncertainty: 'Panel scope restricted to certification-relevant high-materiality refs.' },
  { panel_id: 'governed_exports', artifact: 'operator_surface_snapshot_export.json', fields: ['export_status', 'projection_only', 'verification_state'] }
]
