export type PanelFieldProvenance = {
  panel_id: string
  artifact: string
  fields: string[]
  transformation_path?: string[]
  uncertainty?: string
}

export const PANEL_FIELD_PROVENANCE_MAP: PanelFieldProvenance[] = [
  { panel_id: 'trust_posture', artifact: 'dashboard_freshness_status.json', fields: ['status', 'freshness_window_hours', 'snapshot_last_refreshed_time', 'trace_id'] },
  { panel_id: 'trust_posture', artifact: 'dashboard_publication_sync_audit.json', fields: ['publication_state', 'required_artifact_count', 'records'] },
  { panel_id: 'causal_chain', artifact: 'judgment_application_artifact.json', fields: ['decision_id', 'judgment_ids'], transformation_path: ['judgment_application_artifact.decision_id -> causal_chain.judgment_node'] },
  { panel_id: 'causal_chain', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes', 'timestamp'], transformation_path: ['publication_attempt_record.decision -> causal_chain.control_node'] },
  { panel_id: 'causal_chain', artifact: 'hard_gate_status_record.json', fields: ['readiness_status', 'pass_fail'], transformation_path: ['hard_gate_status_record.readiness_status -> causal_chain.eval_node'] },
  { panel_id: 'causal_chain', artifact: 'serial_bundle_validator_result.json', fields: ['pass'], transformation_path: ['serial_bundle_validator_result.pass -> causal_chain.outcome_node'] },
  { panel_id: 'decision_trace', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes', 'trace_id'] },
  { panel_id: 'decision_trace', artifact: 'judgment_application_artifact.json', fields: ['decision_id', 'judgment_ids'] },
  { panel_id: 'decision_trace', artifact: 'hard_gate_status_record.json', fields: ['gate_name', 'readiness_status'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'current_bottleneck_record.json', fields: ['bottleneck_name', 'impacted_layers'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'current_run_state_record.json', fields: ['current_run_status', 'repair_loop_count'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'hard_gate_status_record.json', fields: ['readiness_status'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'judgment_application_artifact.json', fields: ['decision_id'] },
  { panel_id: 'multi_artifact_correlation', artifact: 'serial_bundle_validator_result.json', fields: ['pass'] },
  { panel_id: 'evidence_strength', artifact: 'dashboard_publication_sync_audit.json', fields: ['records', 'required_artifact_count'] },
  { panel_id: 'evidence_strength', artifact: 'dashboard_freshness_status.json', fields: ['status', 'snapshot_age_hours'] },
  { panel_id: 'evidence_strength', artifact: 'serial_bundle_validator_result.json', fields: ['pass'] },
  { panel_id: 'evidence_strength', artifact: 'dashboard_public_contract_coverage.json', fields: ['covered_artifacts'], uncertainty: 'Coverage artifact does not include uncovered severity by slice; panel computes count only.' },
  { panel_id: 'control_decisions', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes', 'timestamp', 'trace_id'] },
  { panel_id: 'control_decisions', artifact: 'hard_gate_status_record.json', fields: ['gate_name', 'readiness_status', 'pass_fail'] },
  { panel_id: 'judgment_records', artifact: 'judgment_application_artifact.json', fields: ['decision_id', 'judgment_ids', 'consumed_by_control'] },
  { panel_id: 'override_lifecycle', artifact: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', fields: ['overrides.override_id', 'overrides.reason', 'overrides.operator_action'] },
  { panel_id: 'replay_certification', artifact: 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', fields: ['scenario_ids', 'scenario_basis'] },
  { panel_id: 'replay_certification', artifact: 'serial_bundle_validator_result.json', fields: ['pass', 'pass_through_umbrellas', 'empty_batches'] },
  { panel_id: 'replay_certification', artifact: 'governed_promotion_discipline_gate.json', fields: ['promotion_decision', 'allowed_decisions', 'fail_closed'] },
  { panel_id: 'weighted_coverage', artifact: 'dashboard_public_contract_coverage.json', fields: ['covered_artifacts'] },
  { panel_id: 'weighted_coverage', artifact: 'dashboard_publication_manifest.json', fields: ['required_files'] },
  { panel_id: 'trend_control_charts', artifact: 'dashboard_freshness_status.json', fields: ['snapshot_age_hours', 'freshness_window_hours'], uncertainty: 'No historical series artifact published; single-sample chart only.' },
  { panel_id: 'trend_control_charts', artifact: 'publication_attempt_record.json', fields: ['decision'] },
  { panel_id: 'reconciliation', artifact: 'dashboard_freshness_status.json', fields: ['status'] },
  { panel_id: 'reconciliation', artifact: 'publication_attempt_record.json', fields: ['decision'] },
  { panel_id: 'postmortem_outage', artifact: 'refresh_run_record.json', fields: ['outcome', 'failure_class', 'trace_id'] },
  { panel_id: 'tamper_evident_ledger', artifact: 'dashboard_publication_sync_audit.json', fields: ['records.sha256', 'records.artifact'] },
  { panel_id: 'tamper_evident_ledger', artifact: 'serial_bundle_validator_result.json', fields: ['pass'] },
  { panel_id: 'maintain_drift', artifact: 'dashboard_public_contract_coverage.json', fields: ['covered_artifacts'] },
  { panel_id: 'maintain_drift', artifact: 'dashboard_publication_manifest.json', fields: ['required_files'] },
  { panel_id: 'scenario_simulator', artifact: 'rq_next_24_01__umbrella_3__nx_17_failure_hotspot_simulation_pack.json', fields: ['scenario_ids', 'hypotheses'] },
  { panel_id: 'mobile_semantics', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes'] },
  { panel_id: 'policy_visibility', artifact: 'hard_gate_status_record.json', fields: ['gate_name', 'readiness_status', 'required_evidence'] },
  { panel_id: 'policy_visibility', artifact: 'governed_promotion_discipline_gate.json', fields: ['promotion_decision', 'allowed_decisions', 'fail_closed'] },
  { panel_id: 'audit_trail', artifact: 'publication_attempt_record.json', fields: ['publish_attempt_id', 'decision', 'trace_id', 'timestamp'] },
  { panel_id: 'audit_trail', artifact: 'judgment_application_artifact.json', fields: ['decision_id', 'judgment_ids'] },
  { panel_id: 'audit_trail', artifact: 'refresh_run_record.json', fields: ['refresh_run_id', 'run_id', 'trace_id', 'outcome'] },
  { panel_id: 'action_surface', artifact: 'refresh_run_record.json', fields: ['refresh_run_id', 'trigger_mode'] },
  { panel_id: 'action_surface', artifact: 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', fields: ['scenario_ids'] },
  { panel_id: 'action_surface', artifact: 'recommendation_review_surface.json', fields: ['pending_reviews', 'checkpoint_count'], uncertainty: 'Review artifact shape is partially optional; missing keys are blocked.' },
  { panel_id: 'review_queue_surface', artifact: 'recommendation_review_surface.json', fields: ['pending_reviews', 'checkpoint_count', 'status'] },
  { panel_id: 'review_queue_surface', artifact: 'hard_gate_status_record.json', fields: ['readiness_status'] },
  { panel_id: 'misinterpretation_guard', artifact: 'dashboard_freshness_status.json', fields: ['status', 'snapshot_age_hours'] },
  { panel_id: 'misinterpretation_guard', artifact: 'serial_bundle_validator_result.json', fields: ['pass'] },
  { panel_id: 'misinterpretation_guard', artifact: 'publication_attempt_record.json', fields: ['decision', 'reason_codes'] },
  { panel_id: 'operator_coordination_layer', artifact: 'dashboard_publication_manifest.json', fields: ['required_files', 'publication_state'] },
  { panel_id: 'decision_change_conditions', artifact: 'judgment_application_artifact.json', fields: ['change_conditions'] },
  { panel_id: 'evidence_gap_hotspots', artifact: 'readiness_to_expand_validator.json', fields: ['missing_evidence_refs', 'affected_claims', 'materiality_basis', 'certification_relevant'] },
  { panel_id: 'override_hotspots', artifact: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', fields: ['overrides.override_id', 'overrides.operator_action', 'overrides.reason'] },
  { panel_id: 'trust_posture_timeline', artifact: 'operator_trust_closeout_artifact.json', fields: ['snapshots.timestamp', 'snapshots.freshness', 'snapshots.provenance_completeness', 'snapshots.validation_coverage', 'snapshots.replay_status', 'snapshots.trace_completeness'] },
  { panel_id: 'judge_disagreement', artifact: 'cycle_comparator_03_05.json', fields: ['disagreements.dimension', 'disagreements.status', 'disagreements.linked_review_id'] },
  { panel_id: 'policy_regression', artifact: 'cycle_comparator_03_05.json', fields: ['policy_drift', 'candidate_regressions', 'changed_outcomes'] },
  { panel_id: 'capability_readiness', artifact: 'readiness_to_expand_validator.json', fields: ['readiness_state', 'evidence_basis', 'confidence', 'missing_data_indicators'] },
  { panel_id: 'route_efficiency', artifact: 'operator_trust_closeout_artifact.json', fields: ['route_efficiency.route', 'route_efficiency.quality', 'route_efficiency.cost', 'route_efficiency.latency', 'route_efficiency.uncertainty'] },
  { panel_id: 'failure_derived_eval', artifact: 'next_action_outcome_record.json', fields: ['outcomes.failure_id', 'outcomes.eval_case_id', 'outcomes.operationalized'] },
  { panel_id: 'correction_patterns', artifact: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', fields: ['overrides.reason', 'overrides.operator_action', 'overrides.captured_as_learning_signal'] },
  { panel_id: 'review_outcomes', artifact: 'recommendation_review_surface.json', fields: ['pending_reviews.review_id', 'pending_reviews.status', 'pending_reviews.checkpoint'] },
  { panel_id: 'escalation_triggers', artifact: 'hard_gate_status_record.json', fields: ['warn_threshold', 'freeze_threshold', 'block_threshold', 'current_risk_score'] },
  { panel_id: 'escalation_triggers', artifact: 'publication_attempt_record.json', fields: ['decision'], uncertainty: 'Threshold proximity is advisory and separate from decision artifact.' },
  { panel_id: 'cross_run_intelligence', artifact: 'cycle_comparator_03_05.json', fields: ['convergence', 'instability', 'recurring_disagreement', 'repeating_failure_patterns'] },
  { panel_id: 'high_risk_claim_board', artifact: 'readiness_to_expand_validator.json', fields: ['missing_evidence_refs', 'affected_claims'], uncertainty: 'Panel scope restricted to certification-relevant high-materiality refs.' },
  { panel_id: 'governed_exports', artifact: 'operator_surface_snapshot_export.json', fields: ['export_status', 'projection_only', 'verification_state'] },
  { panel_id: 'trust_posture_artifact_browser', artifact: 'operator_trust_closeout_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'trust_posture_diff', artifact: 'operator_trust_closeout_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'capability_readiness_timeline', artifact: 'readiness_to_expand_validator.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'capability_expansion_blockers', artifact: 'readiness_to_expand_validator.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'improvement_recommendation', artifact: 'next_action_recommendation_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'improvement_recommendation_outcomes', artifact: 'next_action_outcome_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'artifact_family_health', artifact: 'dashboard_publication_sync_audit.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'artifact_family_health_trend', artifact: 'dashboard_publication_sync_audit.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'evidence_coverage_density', artifact: 'readiness_to_expand_validator.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'evidence_sufficiency_change', artifact: 'next_action_outcome_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'judge_calibration', artifact: 'confidence_calibration_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'judge_drift', artifact: 'cycle_comparator_03_05.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'human_correction_magnitude', artifact: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'correction_absorption', artifact: 'next_action_outcome_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'policy_deviation', artifact: 'rq_next_24_01__umbrella_4__nx_20_governance_exception_register.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'policy_change_impact', artifact: 'cycle_comparator_03_05.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'route_distribution', artifact: 'operator_trust_closeout_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'quality_vs_cost', artifact: 'operator_trust_closeout_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'latency_vs_quality', artifact: 'operator_trust_closeout_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'retry_validation_failure', artifact: 'serial_bundle_validator_result.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'prompt_version_impact', artifact: 'rq_next_24_01__umbrella_3__nx_14_decision_backtest_harness.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'context_recipe_comparison', artifact: 'rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'context_source_reliability', artifact: 'rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'context_exclusion_rationale', artifact: 'rq_next_24_01__umbrella_2__nx_08_operator_action_admissibility_check.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'contradiction_type', artifact: 'cycle_comparator_03_05.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'cross_artifact_consistency', artifact: 'dashboard_publication_sync_audit.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'schema_drift', artifact: 'dashboard_public_contract_coverage.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'provenance_coverage', artifact: 'dashboard_publication_sync_audit.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'lineage_coverage', artifact: 'serial_bundle_validator_result.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'trace_integrity', artifact: 'refresh_run_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'openlineage_trace_correlation', artifact: 'refresh_run_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'run_bundle_audit', artifact: 'serial_bundle_validator_result.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'promotion_readiness', artifact: 'governed_promotion_discipline_gate.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'promotion_failure', artifact: 'governed_promotion_discipline_gate.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'certification_failure', artifact: 'serial_bundle_validator_result.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'replay_mismatch_root_cause', artifact: 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'replay_stability', artifact: 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'non_determinism_hotspot', artifact: 'drift_trend_continuity_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'error_budget_burn', artifact: 'error_budget_enforcement_outcome.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'budget_breach_history', artifact: 'error_budget_enforcement_outcome.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'incident_correlation', artifact: 'refresh_run_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'alert_quality', artifact: 'hard_gate_status_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'review_queue_load', artifact: 'recommendation_review_surface.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'review_queue_routing_quality', artifact: 'recommendation_review_surface.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'review_debt', artifact: 'recommendation_review_surface.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'review_to_eval_closure', artifact: 'next_action_outcome_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'hitl_override_quality', artifact: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'human_review_reason', artifact: 'recommendation_review_surface.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'decision_log_integrity', artifact: 'judgment_application_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'decision_alternative', artifact: 'judgment_application_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'decision_fragility', artifact: 'rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'counterfactual_study_index', artifact: 'rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'route_canary', artifact: 'rq_next_24_01__umbrella_4__nx_23_controlled_expansion_canary_gate.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'model_tournament', artifact: 'rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'slice_severity', artifact: 'readiness_to_expand_validator.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'missing_eval_slice', artifact: 'next_action_outcome_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'blocking_bottleneck', artifact: 'current_bottleneck_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'roadmap_feed', artifact: 'canonical_roadmap_state_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'control_vs_roadmap_split', artifact: 'canonical_roadmap_state_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'human_review_consumption', artifact: 'recommendation_review_surface.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'quality_sli', artifact: 'dashboard_freshness_status.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'reliability_sli', artifact: 'refresh_run_record.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'capacity_cost_sli', artifact: 'error_budget_enforcement_outcome.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'time_to_insight', artifact: 'operator_trust_closeout_artifact.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'link_integrity', artifact: 'dashboard_publication_manifest.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'dashboard_self_health', artifact: 'dashboard_public_contract_coverage.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'operator_session_path', artifact: 'operator_surface_snapshot_export.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'cognitive_load', artifact: 'operator_surface_snapshot_export.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'panel_materiality_ranking', artifact: 'dashboard_publication_sync_audit.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'panel_retirement_candidate', artifact: 'dashboard_public_contract_coverage.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
  { panel_id: 'certification_gate_reinforcement', artifact: 'governed_promotion_discipline_gate.json', fields: ['verification_state', 'materiality_score'], uncertainty: 'Observational-only; unknown values are blocked.' },
]
