"""Canonical stop-reason taxonomy for bounded roadmap execution surfaces (RDX-006A)."""

from __future__ import annotations

from typing import Final

STOP_REASON_MAX_BATCHES_REACHED: Final[str] = "max_batches_reached"
STOP_REASON_HARD_GATE_STOP: Final[str] = "hard_gate_stop"
STOP_REASON_AUTHORIZATION_BLOCK: Final[str] = "authorization_block"
STOP_REASON_AUTHORIZATION_FREEZE: Final[str] = "authorization_freeze"
STOP_REASON_MISSING_REQUIRED_SIGNAL: Final[str] = "missing_required_signal"
STOP_REASON_EXECUTION_BLOCKED: Final[str] = "execution_blocked"
STOP_REASON_EXECUTION_FAILED: Final[str] = "execution_failed"
STOP_REASON_LOOP_VALIDATION_FAILED: Final[str] = "loop_validation_failed"
STOP_REASON_REPLAY_NOT_READY: Final[str] = "replay_not_ready"
STOP_REASON_INVALID_ROADMAP_STATE: Final[str] = "invalid_roadmap_state"
STOP_REASON_INVALID_PROGRESS_STATE: Final[str] = "invalid_progress_state"
STOP_REASON_CONTRACT_PRECONDITION_FAILED: Final[str] = "contract_precondition_failed"
STOP_REASON_NO_ELIGIBLE_BATCH: Final[str] = "no_eligible_batch"
STOP_REASON_DIMINISHING_RETURNS: Final[str] = "diminishing_returns_detected"
STOP_REASON_REPEATED_FAILURE_PATTERN: Final[str] = "repeated_failure_pattern"
STOP_REASON_UNRESOLVED_BLOCKER_PERSISTS: Final[str] = "unresolved_blocker_persists"
STOP_REASON_RISK_ACCUMULATION_EXCEEDED: Final[str] = "risk_accumulation_threshold_exceeded"
STOP_REASON_PROGRAM_ALIGNMENT_INVALID: Final[str] = "program_alignment_invalid"
STOP_REASON_PROGRAM_PRIORITY_VIOLATION: Final[str] = "program_priority_violation"
STOP_REASON_PROGRAM_BLOCKING_CONDITION: Final[str] = "program_blocking_condition"
STOP_REASON_PROGRAM_DRIFT_DETECTED: Final[str] = "program_drift_detected"

CANONICAL_STOP_REASONS: Final[tuple[str, ...]] = (
    STOP_REASON_MAX_BATCHES_REACHED,
    STOP_REASON_HARD_GATE_STOP,
    STOP_REASON_AUTHORIZATION_BLOCK,
    STOP_REASON_AUTHORIZATION_FREEZE,
    STOP_REASON_MISSING_REQUIRED_SIGNAL,
    STOP_REASON_EXECUTION_BLOCKED,
    STOP_REASON_EXECUTION_FAILED,
    STOP_REASON_LOOP_VALIDATION_FAILED,
    STOP_REASON_REPLAY_NOT_READY,
    STOP_REASON_INVALID_ROADMAP_STATE,
    STOP_REASON_INVALID_PROGRESS_STATE,
    STOP_REASON_CONTRACT_PRECONDITION_FAILED,
    STOP_REASON_NO_ELIGIBLE_BATCH,
    STOP_REASON_DIMINISHING_RETURNS,
    STOP_REASON_REPEATED_FAILURE_PATTERN,
    STOP_REASON_UNRESOLVED_BLOCKER_PERSISTS,
    STOP_REASON_RISK_ACCUMULATION_EXCEEDED,
    STOP_REASON_PROGRAM_ALIGNMENT_INVALID,
    STOP_REASON_PROGRAM_PRIORITY_VIOLATION,
    STOP_REASON_PROGRAM_BLOCKING_CONDITION,
    STOP_REASON_PROGRAM_DRIFT_DETECTED,
)
