#!/usr/bin/env python3
"""
Generate ecosystem health report for the spectrum-systems governance architecture.

Reads from:
- ecosystem/ecosystem-registry.json
- ecosystem/system-registry.json
- ecosystem/maturity-tracker.json
- governance/reports/contract-dependency-graph.json
- artifacts/policy-engine-report.json  (optional — generated by policy engine)
- contracts/standards-manifest.json

Outputs:
- governance/reports/ecosystem-health.json          (machine-readable)
- docs/governance-reports/ecosystem-health-report.md (human-readable summary)
- docs/governance-reports/ecosystem-dashboard.md     (lightweight dashboard)

Exit codes
----------
0 — success (warnings do not cause failure)
1 — error generating report
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]

ECOSYSTEM_REGISTRY_PATH = REPO_ROOT / "ecosystem" / "ecosystem-registry.json"
SYSTEM_REGISTRY_PATH = REPO_ROOT / "ecosystem" / "system-registry.json"
MATURITY_TRACKER_PATH = REPO_ROOT / "ecosystem" / "maturity-tracker.json"
CONTRACT_GRAPH_PATH = REPO_ROOT / "governance" / "reports" / "contract-dependency-graph.json"
POLICY_REPORT_PATH = REPO_ROOT / "artifacts" / "policy-engine-report.json"
STANDARDS_MANIFEST_PATH = REPO_ROOT / "contracts" / "standards-manifest.json"
MANIFESTS_DIR = REPO_ROOT / "governance" / "examples" / "manifests"

HEALTH_JSON_PATH = REPO_ROOT / "governance" / "reports" / "ecosystem-health.json"
HEALTH_REPORT_PATH = REPO_ROOT / "docs" / "governance-reports" / "ecosystem-health-report.md"
DASHBOARD_PATH = REPO_ROOT / "docs" / "governance-reports" / "ecosystem-dashboard.md"

# Maturity scoring thresholds for L1–L10 estimate
# Each category contributes to a total raw score; raw score maps to a level.
MATURITY_CATEGORIES = [
    "governance_artifacts",
    "contract_compliance",
    "schema_alignment",
    "ci_enforcement",
    "evaluation_evidence",
    "documentation",
]

CATEGORY_WEIGHTS = {
    "governance_artifacts": 2,
    "contract_compliance": 2,
    "schema_alignment": 1,
    "ci_enforcement": 2,
    "evaluation_evidence": 2,
    "documentation": 1,
}

STATE_SCORES = {"compliant": 2, "partial": 1, "missing": 0}


# ─────────────────────────────────────────────────────────────────────────────
# Data loaders
# ─────────────────────────────────────────────────────────────────────────────

def load_json(path: Path) -> Optional[dict]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None


def load_list_json(path: Path) -> Optional[list]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, list) else None
    except FileNotFoundError:
        return None


def load_ecosystem_registry() -> Dict[str, dict]:
    data = load_json(ECOSYSTEM_REGISTRY_PATH) or {}
    return {
        entry["repo_name"]: entry
        for entry in data.get("repositories", [])
        if entry.get("repo_name")
    }


def load_system_registry() -> Dict[str, dict]:
    entries = load_list_json(SYSTEM_REGISTRY_PATH) or []
    return {
        entry["system_id"]: entry
        for entry in entries
        if entry.get("system_id")
    }


def load_maturity_tracker() -> Dict[str, dict]:
    entries = load_list_json(MATURITY_TRACKER_PATH) or []
    return {
        entry["system_id"]: entry
        for entry in entries
        if entry.get("system_id")
    }


def load_contract_graph() -> dict:
    return load_json(CONTRACT_GRAPH_PATH) or {}


def load_policy_report() -> dict:
    return load_json(POLICY_REPORT_PATH) or {}


def load_standards_manifest() -> Dict[str, dict]:
    data = load_json(STANDARDS_MANIFEST_PATH) or {}
    return {
        c["artifact_type"]: c
        for c in data.get("contracts", [])
        if c.get("artifact_type")
    }


def load_governance_manifests() -> Dict[str, dict]:
    manifests: Dict[str, dict] = {}
    for mpath in sorted(MANIFESTS_DIR.glob("*.json")):
        data = load_json(mpath)
        if not data:
            continue
        repo_name = data.get("repo_name") or mpath.stem.split(".")[0]
        manifests[repo_name] = data
    return manifests


# ─────────────────────────────────────────────────────────────────────────────
# Maturity scoring
# ─────────────────────────────────────────────────────────────────────────────

def score_governance_artifacts(
    repo_name: str,
    repo_entry: dict,
    manifests: Dict[str, dict],
) -> str:
    """Does the repo have a governance manifest when required?"""
    if not repo_entry.get("manifest_required", False):
        return "compliant"
    if repo_name in manifests:
        return "compliant"
    if repo_entry.get("status") in ("planned", "experimental"):
        return "partial"
    return "missing"


def score_contract_compliance(
    repo_name: str,
    contract_graph_repos: Dict[str, dict],
) -> str:
    """Is the repo contract-compliant per the enforcement graph?"""
    repo_data = contract_graph_repos.get(repo_name)
    if repo_data is None:
        return "missing"
    status = repo_data.get("validation_status", "")
    if status == "pass":
        return "compliant"
    if status in ("warning", "not_yet_enforceable", "governance-repo"):
        return "partial"
    return "missing"


def score_schema_alignment(
    repo_name: str,
    repo_entry: dict,
    standards: Dict[str, dict],
    manifests: Dict[str, dict],
) -> str:
    """Do all declared contracts resolve to known schema versions?"""
    manifest = manifests.get(repo_name)
    if manifest is None:
        if not repo_entry.get("manifest_required", False):
            return "compliant"
        return "missing"
    declared = manifest.get("contracts", {})
    if not declared:
        return "compliant"
    mismatches = 0
    for artifact_type, pinned_version in declared.items():
        canonical = standards.get(artifact_type)
        if canonical is None:
            mismatches += 1
        elif canonical.get("schema_version") != pinned_version:
            mismatches += 1
    if mismatches == 0:
        return "compliant"
    if mismatches < len(declared):
        return "partial"
    return "missing"


def score_ci_enforcement(repo_name: str, repo_entry: dict) -> str:
    """
    Does the repo have CI enabled?
    For the governance repo we always return compliant.
    For operational repos we infer from repo_type and status.
    """
    if repo_entry.get("repo_type") == "governance":
        return "compliant"
    status = repo_entry.get("status", "")
    if status == "active":
        return "compliant"
    if status in ("experimental",):
        return "partial"
    return "missing"


def score_evaluation_evidence(
    repo_name: str,
    system_entry: Optional[dict],
    maturity_entry: Optional[dict],
) -> str:
    """Does the system have evaluation evidence (maturity level > 3, or evidence listed)?"""
    if system_entry is None and maturity_entry is None:
        return "missing"
    level = None
    if maturity_entry:
        level = maturity_entry.get("current_level")
    elif system_entry:
        level = system_entry.get("maturity_level")
    if level is not None:
        if level >= 5:
            return "compliant"
        if level >= 3:
            return "partial"
    evidence = []
    if maturity_entry:
        evidence = maturity_entry.get("evidence", [])
    if evidence:
        return "partial"
    return "missing"


def score_documentation(repo_entry: dict) -> str:
    """Does the repo have a description field (basic proxy for documentation completeness)?"""
    desc = repo_entry.get("description", "").strip()
    if len(desc) >= 30:
        return "compliant"
    if desc:
        return "partial"
    return "missing"


def compute_maturity_score(category_scores: Dict[str, str]) -> Tuple[int, int]:
    """
    Return (raw_score, max_score).
    raw_score / max_score * 10 maps to L1–L10.
    """
    raw = 0
    max_raw = 0
    for cat, weight in CATEGORY_WEIGHTS.items():
        state = category_scores.get(cat, "missing")
        raw += STATE_SCORES.get(state, 0) * weight
        max_raw += STATE_SCORES["compliant"] * weight
    return raw, max_raw


def raw_to_maturity_level(raw: int, max_raw: int) -> int:
    """Map raw score to L1–L10."""
    if max_raw == 0:
        return 1
    ratio = raw / max_raw
    level = max(1, min(10, round(ratio * 10)))
    return level


# ─────────────────────────────────────────────────────────────────────────────
# Per-repo health record builder
# ─────────────────────────────────────────────────────────────────────────────

def build_repo_record(
    repo_name: str,
    repo_entry: dict,
    system_entry: Optional[dict],
    maturity_entry: Optional[dict],
    contract_graph_repos: Dict[str, dict],
    standards: Dict[str, dict],
    manifests: Dict[str, dict],
    policy_results_by_repo: Dict[str, List[dict]],
) -> dict:
    repo_type = repo_entry.get("repo_type", "")
    architecture_layer = repo_entry.get("layer", "")
    system_id = repo_entry.get("system_id", "")
    status = repo_entry.get("status", "")

    # Maturity scoring
    cat_gov = score_governance_artifacts(repo_name, repo_entry, manifests)
    cat_contract = score_contract_compliance(repo_name, contract_graph_repos)
    cat_schema = score_schema_alignment(repo_name, repo_entry, standards, manifests)
    cat_ci = score_ci_enforcement(repo_name, repo_entry)
    cat_eval = score_evaluation_evidence(repo_name, system_entry, maturity_entry)
    cat_doc = score_documentation(repo_entry)

    category_scores = {
        "governance_artifacts": cat_gov,
        "contract_compliance": cat_contract,
        "schema_alignment": cat_schema,
        "ci_enforcement": cat_ci,
        "evaluation_evidence": cat_eval,
        "documentation": cat_doc,
    }

    raw, max_raw = compute_maturity_score(category_scores)
    maturity_level = raw_to_maturity_level(raw, max_raw)

    # Governance status from policy engine results
    repo_policy_results = policy_results_by_repo.get(repo_name, [])
    has_policy_errors = any(
        r.get("severity") == "error" and r.get("status") == "fail"
        for r in repo_policy_results
    )
    has_policy_warnings = any(
        r.get("status") in ("warning", "fail") and r.get("severity") != "error"
        for r in repo_policy_results
    )
    if has_policy_errors:
        governance_status = "fail"
    elif has_policy_warnings:
        governance_status = "warning"
    elif repo_type == "governance":
        governance_status = "compliant"
    else:
        governance_status = "compliant" if cat_gov == "compliant" else "partial"

    # Contract status from enforcement graph
    cg_repo = contract_graph_repos.get(repo_name)
    if cg_repo:
        contract_status = cg_repo.get("validation_status", "not_yet_enforceable")
    elif repo_entry.get("manifest_required", False):
        contract_status = "not_yet_enforceable"
    else:
        contract_status = "n/a"

    # Schema status
    schema_status = cat_schema

    # CI status
    ci_status = cat_ci

    # Notes
    notes_parts: List[str] = []
    if status in ("planned", "experimental"):
        notes_parts.append(f"repo is {status}")
    for cat, state in category_scores.items():
        if state == "missing":
            notes_parts.append(f"{cat} missing")
    notes = "; ".join(notes_parts) if notes_parts else ""

    record = {
        "repo_name": repo_name,
        "system_id": system_id,
        "repo_type": repo_type,
        "architecture_layer": architecture_layer,
        "status": status,
        "governance_status": governance_status,
        "contract_status": contract_status,
        "schema_status": schema_status,
        "ci_status": ci_status,
        "maturity_score": {
            "raw": raw,
            "max": max_raw,
            "categories": category_scores,
        },
        "maturity_level": maturity_level,
        "notes": notes,
    }
    return record


# ─────────────────────────────────────────────────────────────────────────────
# Aggregate health computation
# ─────────────────────────────────────────────────────────────────────────────

def compute_health_summary(repo_records: List[dict]) -> dict:
    total = len(repo_records)
    governance_counts: Dict[str, int] = {"compliant": 0, "warning": 0, "fail": 0, "partial": 0}
    contract_counts: Dict[str, int] = {}
    schema_counts: Dict[str, int] = {}
    ci_counts: Dict[str, int] = {}
    missing_artifacts: List[str] = []
    not_yet_enforceable: List[str] = []

    for rec in repo_records:
        g = rec["governance_status"]
        governance_counts[g] = governance_counts.get(g, 0) + 1

        c = rec["contract_status"]
        contract_counts[c] = contract_counts.get(c, 0) + 1

        s = rec["schema_status"]
        schema_counts[s] = schema_counts.get(s, 0) + 1

        ci = rec["ci_status"]
        ci_counts[ci] = ci_counts.get(ci, 0) + 1

        if rec["maturity_score"]["categories"].get("governance_artifacts") == "missing":
            missing_artifacts.append(rec["repo_name"])

        if rec["contract_status"] == "not_yet_enforceable":
            not_yet_enforceable.append(rec["repo_name"])

    overall_health = "healthy"
    if governance_counts.get("fail", 0) > 0 or contract_counts.get("fail", 0) > 0:
        overall_health = "failing"
    elif (
        governance_counts.get("warning", 0) > 0
        or governance_counts.get("partial", 0) > 0
        or contract_counts.get("warning", 0) > 0
        or not_yet_enforceable
    ):
        overall_health = "warning"

    return {
        "overall_health": overall_health,
        "total_repos": total,
        "governance_compliance": governance_counts,
        "contract_alignment": contract_counts,
        "schema_integrity": schema_counts,
        "ci_enforcement": ci_counts,
        "repos_missing_required_artifacts": missing_artifacts,
        "repos_not_yet_enforceable": not_yet_enforceable,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Report writers
# ─────────────────────────────────────────────────────────────────────────────

STATUS_EMOJI = {
    "compliant": "✅",
    "pass": "✅",
    "partial": "⚠️",
    "warning": "⚠️",
    "fail": "❌",
    "missing": "❌",
    "not_yet_enforceable": "🔲",
    "n/a": "—",
    "healthy": "✅",
    "failing": "❌",
    "governance-repo": "🏛",
}


def _e(status: str) -> str:
    return STATUS_EMOJI.get(status, status)


def write_health_json(
    repo_records: List[dict],
    summary: dict,
    generated_at: str,
) -> None:
    HEALTH_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
    payload = {
        "schema_version": "1.0.0",
        "generated_at": generated_at,
        "summary": summary,
        "repos": sorted(repo_records, key=lambda r: r["repo_name"]),
    }
    HEALTH_JSON_PATH.write_text(
        json.dumps(payload, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def write_health_report(
    repo_records: List[dict],
    summary: dict,
    generated_at: str,
) -> None:
    HEALTH_REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)

    gc = summary["governance_compliance"]
    ca = summary["contract_alignment"]
    si = summary["schema_integrity"]
    ci = summary["ci_enforcement"]

    lines: List[str] = []
    lines.append("# Ecosystem Health Report\n")
    lines.append(f"Generated: {generated_at}  ")
    lines.append("Sources: `ecosystem/ecosystem-registry.json`, `governance/reports/contract-dependency-graph.json`, `artifacts/policy-engine-report.json`\n")
    lines.append(f"**Overall Health**: {_e(summary['overall_health'])} `{summary['overall_health'].upper()}`\n")

    lines.append("## Summary\n")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Repos Inspected | {summary['total_repos']} |")
    lines.append(f"| Overall Health | {_e(summary['overall_health'])} {summary['overall_health']} |")
    lines.append("")

    # Governance Compliance
    lines.append("## Governance Compliance\n")
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    for status, count in sorted(gc.items()):
        lines.append(f"| {_e(status)} {status} | {count} |")
    lines.append("")

    # Contract Alignment
    lines.append("## Contract Alignment\n")
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    for status, count in sorted(ca.items()):
        lines.append(f"| {_e(status)} {status} | {count} |")
    lines.append("")

    # Schema Integrity
    lines.append("## Schema Integrity\n")
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    for status, count in sorted(si.items()):
        lines.append(f"| {_e(status)} {status} | {count} |")
    lines.append("")

    # CI Enforcement
    lines.append("## CI Enforcement\n")
    lines.append("| Status | Count |")
    lines.append("|--------|-------|")
    for status, count in sorted(ci.items()):
        lines.append(f"| {_e(status)} {status} | {count} |")
    lines.append("")

    # Repository Coverage
    lines.append("## Repository Coverage\n")
    lines.append("| Repo | Layer | System ID | Governance | Contract | Schema | CI | Maturity Level |")
    lines.append("|------|-------|-----------|-----------|---------|--------|-----|----------------|")
    for rec in sorted(repo_records, key=lambda r: r["repo_name"]):
        lines.append(
            f"| `{rec['repo_name']}` "
            f"| {rec['architecture_layer']} "
            f"| {rec['system_id'] or '—'} "
            f"| {_e(rec['governance_status'])} {rec['governance_status']} "
            f"| {_e(rec['contract_status'])} {rec['contract_status']} "
            f"| {_e(rec['schema_status'])} {rec['schema_status']} "
            f"| {_e(rec['ci_status'])} {rec['ci_status']} "
            f"| L{rec['maturity_level']} |"
        )
    lines.append("")

    # Missing Required Artifacts
    missing = summary["repos_missing_required_artifacts"]
    lines.append("## Repos Missing Required Governance Artifacts\n")
    if missing:
        for r in missing:
            lines.append(f"- `{r}`")
    else:
        lines.append("All repos with `manifest_required=true` have governance manifests. ✅")
    lines.append("")

    # Not Yet Enforceable
    nye = summary["repos_not_yet_enforceable"]
    lines.append("## Repos Not Yet Enforceable\n")
    if nye:
        for r in nye:
            lines.append(f"- `{r}` 🔲")
    else:
        lines.append("All repos are enforceable (governance manifests present). ✅")
    lines.append("")

    HEALTH_REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def write_dashboard(repo_records: List[dict], generated_at: str) -> None:
    DASHBOARD_PATH.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = []
    lines.append("# Ecosystem Dashboard\n")
    lines.append(f"Generated: {generated_at}\n")
    lines.append("Quick visibility into ecosystem health. Full detail: [ecosystem-health-report.md](ecosystem-health-report.md)\n")
    lines.append("| Repo | Layer | System ID | Governance | Contract | Maturity |")
    lines.append("|------|-------|-----------|-----------|---------|---------|")
    for rec in sorted(repo_records, key=lambda r: r["repo_name"]):
        lines.append(
            f"| `{rec['repo_name']}` "
            f"| {rec['architecture_layer']} "
            f"| {rec['system_id'] or '—'} "
            f"| {_e(rec['governance_status'])} {rec['governance_status']} "
            f"| {_e(rec['contract_status'])} {rec['contract_status']} "
            f"| L{rec['maturity_level']} |"
        )
    lines.append("")

    DASHBOARD_PATH.write_text("\n".join(lines), encoding="utf-8")


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────

def main() -> int:
    try:
        ecosystem_registry = load_ecosystem_registry()
        system_registry = load_system_registry()
        maturity_tracker = load_maturity_tracker()
        contract_graph = load_contract_graph()
        policy_report = load_policy_report()
        standards = load_standards_manifest()
        manifests = load_governance_manifests()
    except Exception as exc:
        print(f"[ecosystem-health] ERROR loading inputs: {exc}", file=sys.stderr)
        return 1

    # Build lookup of contract graph repos keyed by repo_name
    contract_graph_repos: Dict[str, dict] = {
        r["repo_name"]: r
        for r in contract_graph.get("repos", [])
        if r.get("repo_name")
    }

    # Build policy results keyed by subject (repo_name)
    policy_results_by_repo: Dict[str, List[dict]] = {}
    for result in policy_report.get("results", []):
        subject = result.get("subject", "")
        policy_results_by_repo.setdefault(subject, []).append(result)

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    repo_records: List[dict] = []
    for repo_name, repo_entry in sorted(ecosystem_registry.items()):
        system_id = repo_entry.get("system_id", "")
        system_entry = system_registry.get(repo_name) or system_registry.get(system_id)
        maturity_entry = maturity_tracker.get(repo_name) or maturity_tracker.get(system_id)

        record = build_repo_record(
            repo_name=repo_name,
            repo_entry=repo_entry,
            system_entry=system_entry,
            maturity_entry=maturity_entry,
            contract_graph_repos=contract_graph_repos,
            standards=standards,
            manifests=manifests,
            policy_results_by_repo=policy_results_by_repo,
        )
        repo_records.append(record)

    summary = compute_health_summary(repo_records)

    write_health_json(repo_records, summary, generated_at)
    write_health_report(repo_records, summary, generated_at)
    write_dashboard(repo_records, generated_at)

    print(f"[ecosystem-health] Generated health report for {len(repo_records)} repos.")
    print(f"[ecosystem-health] Overall health: {summary['overall_health'].upper()}")
    if summary["repos_missing_required_artifacts"]:
        print("[ecosystem-health] Repos missing required artifacts:")
        for r in summary["repos_missing_required_artifacts"]:
            print(f"  - {r}")
    if summary["repos_not_yet_enforceable"]:
        print("[ecosystem-health] Repos not yet enforceable:")
        for r in summary["repos_not_yet_enforceable"]:
            print(f"  - {r}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
