#!/usr/bin/env python3
"""Generate docs/roadmaps/system_roadmap.md from contracts/examples/system_roadmap.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def _load_json(path: Path) -> dict[str, Any]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError("system roadmap payload must be a JSON object")
    return payload


def _abbr(batch_id: str) -> str:
    prefix, number = batch_id.split("-", 1)
    return f"{prefix}{number}"


def _render_markdown(roadmap: dict[str, Any], source_json: Path) -> str:
    batches = roadmap["batches"]
    lines = [
        "# Spectrum Systems — System Roadmap",
        "",
        "<!-- Generated by scripts/sync_system_roadmap_markdown.py; do not hand-edit tables. -->",
        "",
        "**Authority status:** ACTIVE ROADMAP AUTHORITY",
        "",
        f"- System source of truth (machine-readable): `{source_json.as_posix()}`",
        "- Contract authority: `contracts/schemas/system_roadmap.schema.json`",
        "- Compatibility transition rule: `docs/roadmap/system_roadmap.md` is a required parseable operational mirror",
        "",
        "## Abbreviated Batch View",
        "",
        "| Batch | Summary |",
        "| --- | --- |",
    ]
    for batch in batches:
        lines.append(f"| {_abbr(batch['batch_id'])} | {batch['title']} |")

    lines.extend([
        "",
        "## Governed Batch Table",
        "",
        "| batch_id | acronym | title | status | depends_on | hard_gate |",
        "| --- | --- | --- | --- | --- | --- |",
    ])
    for batch in batches:
        deps = ", ".join(batch["depends_on"]) if batch["depends_on"] else "—"
        lines.append(
            f"| {batch['batch_id']} | {batch['acronym']} | {batch['title']} | {batch['status']} | {deps} | {str(batch['hard_gate']).lower()} |"
        )

    lines.extend([
        "",
        "Execution automation must read the governed JSON artifact, validate against schema before selection, and fail closed on invalid roadmap state.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Synchronize human-readable roadmap markdown from governed system_roadmap JSON.")
    parser.add_argument(
        "--roadmap-json",
        type=Path,
        default=Path("contracts/examples/system_roadmap.json"),
    )
    parser.add_argument(
        "--markdown-out",
        type=Path,
        default=Path("docs/roadmaps/system_roadmap.md"),
    )
    args = parser.parse_args()

    roadmap = _load_json(args.roadmap_json)
    markdown = _render_markdown(roadmap, args.roadmap_json)
    args.markdown_out.write_text(markdown, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
