export type SurfaceStatus = 'renderable' | 'blocked' | 'warning'

export type DashboardSurfaceContract = {
  panel_id: string
  title: string
  artifact_family: string
  contract_source: string
  owning_system: 'RIL' | 'CDE' | 'TLC' | 'PQX' | 'FRE' | 'SEL' | 'PRG'
  render_gate_dependency: string[]
  freshness_dependency: string[]
  provenance_requirements: string[]
  blocked_state_behavior: 'hide_panel' | 'render_blocked_diagnostic'
  allowed_statuses: SurfaceStatus[]
  certification_relevant: boolean
  high_risk: boolean
  mobile_critical: boolean
}

export const DASHBOARD_SURFACE_CONTRACT_REGISTRY: DashboardSurfaceContract[] = [
  {
    panel_id: 'trust_posture',
    title: 'Trust posture',
    artifact_family: 'dashboard_freshness_status + dashboard_publication_sync_audit',
    contract_source: 'dashboard/public/dashboard_freshness_status.json',
    owning_system: 'SEL',
    render_gate_dependency: ['dashboard_freshness_status.json', 'dashboard_publication_manifest.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['field-level trace for freshness, validation, provenance, replay, renderability'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'causal_chain',
    title: 'Causal chain',
    artifact_family: 'publication_attempt_record + judgment_application_artifact + hard_gate_status_record + serial_bundle_validator_result',
    contract_source: 'dashboard/public/publication_attempt_record.json',
    owning_system: 'TLC',
    render_gate_dependency: ['publication_attempt_record.json', 'judgment_application_artifact.json', 'hard_gate_status_record.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['publication_attempt_record.json', 'serial_bundle_validator_result.json'],
    provenance_requirements: ['artifact-linked edge trace for eval → judgment → control → outcome'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'decision_trace',
    title: 'Decision trace',
    artifact_family: 'publication_attempt_record + judgment_application_artifact + hard_gate_status_record',
    contract_source: 'dashboard/public/judgment_application_artifact.json',
    owning_system: 'RIL',
    render_gate_dependency: ['publication_attempt_record.json', 'judgment_application_artifact.json', 'hard_gate_status_record.json'],
    freshness_dependency: ['publication_attempt_record.json'],
    provenance_requirements: ['decision reasons must be field-traceable to artifacts'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'multi_artifact_correlation',
    title: 'Multi-artifact correlation',
    artifact_family: 'current_bottleneck_record + current_run_state_record + hard_gate_status_record + judgment_application_artifact + serial_bundle_validator_result',
    contract_source: 'dashboard/public/current_bottleneck_record.json',
    owning_system: 'PRG',
    render_gate_dependency: ['current_bottleneck_record.json', 'current_run_state_record.json', 'hard_gate_status_record.json', 'judgment_application_artifact.json'],
    freshness_dependency: ['current_run_state_record.json', 'serial_bundle_validator_result.json'],
    provenance_requirements: ['correlation rows must preserve source artifact and consumed fields'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: false,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'evidence_strength',
    title: 'Evidence strength',
    artifact_family: 'dashboard_publication_sync_audit + dashboard_freshness_status + serial_bundle_validator_result + dashboard_public_contract_coverage',
    contract_source: 'dashboard/public/dashboard_publication_sync_audit.json',
    owning_system: 'CDE',
    render_gate_dependency: ['dashboard_publication_sync_audit.json', 'dashboard_freshness_status.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['dimension-level rows for provenance depth/agreement/freshness/validation/replay'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'control_decisions',
    title: 'Control decisions',
    artifact_family: 'publication_attempt_record + hard_gate_status_record',
    contract_source: 'dashboard/public/publication_attempt_record.json',
    owning_system: 'SEL',
    render_gate_dependency: ['publication_attempt_record.json', 'hard_gate_status_record.json'],
    freshness_dependency: ['publication_attempt_record.json'],
    provenance_requirements: ['decision code and reason_codes trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'judgment_records',
    title: 'Judgment records',
    artifact_family: 'judgment_application_artifact',
    contract_source: 'dashboard/public/judgment_application_artifact.json',
    owning_system: 'RIL',
    render_gate_dependency: ['judgment_application_artifact.json'],
    freshness_dependency: ['judgment_application_artifact.json'],
    provenance_requirements: ['judgment_ids and decision_id trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'override_lifecycle',
    title: 'Override lifecycle',
    artifact_family: 'operator_override_capture',
    contract_source: 'dashboard/public/rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json',
    owning_system: 'SEL',
    render_gate_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'],
    freshness_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'],
    provenance_requirements: ['override_id and reason trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'replay_certification',
    title: 'Replay and certification',
    artifact_family: 'recommendation_replay_pack + serial_bundle_validator_result + governed_promotion_discipline_gate',
    contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json',
    owning_system: 'CDE',
    render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['serial_bundle_validator_result.json'],
    provenance_requirements: ['scenario ids and pass/fail trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'weighted_coverage',
    title: 'Weighted coverage',
    artifact_family: 'dashboard_public_contract_coverage + dashboard_publication_manifest',
    contract_source: 'dashboard/public/dashboard_public_contract_coverage.json',
    owning_system: 'PRG',
    render_gate_dependency: ['dashboard_public_contract_coverage.json', 'dashboard_publication_manifest.json'],
    freshness_dependency: ['dashboard_public_contract_coverage.json'],
    provenance_requirements: ['covered_artifacts and required_files trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked', 'warning'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'trend_control_charts',
    title: 'Trend control charts',
    artifact_family: 'dashboard_freshness_status + refresh_run_record + publication_attempt_record',
    contract_source: 'dashboard/public/dashboard_freshness_status.json',
    owning_system: 'TLC',
    render_gate_dependency: ['dashboard_freshness_status.json', 'refresh_run_record.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['threshold + observed values trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: false,
    high_risk: false,
    mobile_critical: false
  },
  {
    panel_id: 'reconciliation',
    title: 'High-risk reconciliation',
    artifact_family: 'dashboard_freshness_status + publication_attempt_record',
    contract_source: 'dashboard/public/publication_attempt_record.json',
    owning_system: 'SEL',
    render_gate_dependency: ['dashboard_freshness_status.json', 'publication_attempt_record.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['dual-source verdict disagreement trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'postmortem_outage',
    title: 'Postmortem and outage',
    artifact_family: 'refresh_run_record + publication_attempt_record + drift_trend_continuity_artifact',
    contract_source: 'dashboard/public/refresh_run_record.json',
    owning_system: 'FRE',
    render_gate_dependency: ['refresh_run_record.json', 'publication_attempt_record.json'],
    freshness_dependency: ['refresh_run_record.json'],
    provenance_requirements: ['failure class and trace link'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: false,
    high_risk: false,
    mobile_critical: false
  },
  {
    panel_id: 'tamper_evident_ledger',
    title: 'Tamper-evident publication ledger',
    artifact_family: 'dashboard_publication_sync_audit + serial_bundle_validator_result',
    contract_source: 'dashboard/public/dashboard_publication_sync_audit.json',
    owning_system: 'CDE',
    render_gate_dependency: ['dashboard_publication_sync_audit.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['dashboard_publication_sync_audit.json'],
    provenance_requirements: ['record-level verification flags trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'maintain_drift',
    title: 'Maintain and drift',
    artifact_family: 'dashboard_publication_manifest + dashboard_public_contract_coverage + operator_override_capture',
    contract_source: 'dashboard/public/dashboard_publication_manifest.json',
    owning_system: 'PRG',
    render_gate_dependency: ['dashboard_publication_manifest.json', 'dashboard_public_contract_coverage.json'],
    freshness_dependency: ['dashboard_publication_manifest.json'],
    provenance_requirements: ['dead panel and mismatch signals trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked', 'warning'],
    certification_relevant: false,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'scenario_simulator',
    title: 'Governed scenario simulator',
    artifact_family: 'governed fixture bundle',
    contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_17_failure_hotspot_simulation_pack.json',
    owning_system: 'PQX',
    render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_17_failure_hotspot_simulation_pack.json'],
    freshness_dependency: ['rq_next_24_01__umbrella_3__nx_17_failure_hotspot_simulation_pack.json'],
    provenance_requirements: ['fixture scenario identifiers trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: false,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'mobile_semantics',
    title: 'Mobile operator semantics',
    artifact_family: 'read-model diagnostics',
    contract_source: 'dashboard/lib/read_model/dashboard_read_model_compiler.ts',
    owning_system: 'TLC',
    render_gate_dependency: ['dashboard_freshness_status.json', 'publication_attempt_record.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['blocked-state and high-risk cues trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'policy_visibility',
    title: 'Policy visibility',
    artifact_family: 'hard_gate_status_record + governed_promotion_discipline_gate',
    contract_source: 'dashboard/public/hard_gate_status_record.json',
    owning_system: 'SEL',
    render_gate_dependency: ['hard_gate_status_record.json', 'governed_promotion_discipline_gate.json'],
    freshness_dependency: ['hard_gate_status_record.json'],
    provenance_requirements: ['policy threshold and enforcement rule fields rendered read-only'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'audit_trail',
    title: 'Audit trail',
    artifact_family: 'publication_attempt_record + judgment_application_artifact + refresh_run_record + serial_bundle_validator_result',
    contract_source: 'dashboard/public/publication_attempt_record.json',
    owning_system: 'CDE',
    render_gate_dependency: ['publication_attempt_record.json', 'judgment_application_artifact.json', 'refresh_run_record.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['publication_attempt_record.json', 'refresh_run_record.json'],
    provenance_requirements: ['decision history, transitions, and trace lineage are artifact-linked'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'action_surface',
    title: 'Governed non-decision actions',
    artifact_family: 'refresh_run_record + recommendation_replay_pack + recommendation_review_surface',
    contract_source: 'dashboard/public/refresh_run_record.json',
    owning_system: 'TLC',
    render_gate_dependency: ['refresh_run_record.json', 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', 'recommendation_review_surface.json'],
    freshness_dependency: ['refresh_run_record.json'],
    provenance_requirements: ['action list must be refresh/replay/review-handoff only and artifact traceable'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'review_queue_surface',
    title: 'Review queue surface',
    artifact_family: 'recommendation_review_surface + hard_gate_status_record',
    contract_source: 'dashboard/public/recommendation_review_surface.json',
    owning_system: 'RIL',
    render_gate_dependency: ['recommendation_review_surface.json', 'hard_gate_status_record.json'],
    freshness_dependency: ['recommendation_review_surface.json'],
    provenance_requirements: ['pending review records and HITL checkpoints are artifact-backed'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'misinterpretation_guard',
    title: 'Misinterpretation guard',
    artifact_family: 'dashboard_freshness_status + serial_bundle_validator_result + publication_attempt_record',
    contract_source: 'dashboard/public/dashboard_freshness_status.json',
    owning_system: 'FRE',
    render_gate_dependency: ['dashboard_freshness_status.json', 'serial_bundle_validator_result.json', 'publication_attempt_record.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['low-evidence and disagreement states force explicit uncertainty labels'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'operator_coordination_layer',
    title: 'Operator coordination layer',
    artifact_family: 'dashboard coordination read model',
    contract_source: 'dashboard/lib/read_model/dashboard_read_model_compiler.ts',
    owning_system: 'TLC',
    render_gate_dependency: ['dashboard_publication_manifest.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['jobs-to-be-done grouping must map to artifact-backed panels only'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  { panel_id: 'decision_change_conditions', title: 'Decision change conditions', artifact_family: 'judgment_application_artifact', contract_source: 'dashboard/public/judgment_application_artifact.json', owning_system: 'RIL', render_gate_dependency: ['judgment_application_artifact.json'], freshness_dependency: ['judgment_application_artifact.json'], provenance_requirements: ['change conditions must be directly artifact-backed'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: true },
  { panel_id: 'evidence_gap_hotspots', title: 'Evidence gap hotspots', artifact_family: 'readiness_to_expand_validator', contract_source: 'dashboard/public/readiness_to_expand_validator.json', owning_system: 'CDE', render_gate_dependency: ['readiness_to_expand_validator.json'], freshness_dependency: ['readiness_to_expand_validator.json'], provenance_requirements: ['missing evidence refs and affected claims must be drillable'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: true },
  { panel_id: 'override_hotspots', title: 'Override hotspots', artifact_family: 'operator_override_capture', contract_source: 'dashboard/public/rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', owning_system: 'SEL', render_gate_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'], freshness_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'], provenance_requirements: ['override concentration and recurrence rows must remain artifact-backed'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: true },
  { panel_id: 'trust_posture_timeline', title: 'Trust posture snapshot timeline', artifact_family: 'operator_trust_closeout_artifact', contract_source: 'dashboard/public/operator_trust_closeout_artifact.json', owning_system: 'FRE', render_gate_dependency: ['operator_trust_closeout_artifact.json'], freshness_dependency: ['operator_trust_closeout_artifact.json'], provenance_requirements: ['per-dimension trust posture snapshots must be preserved'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'judge_disagreement', title: 'Judge disagreement surface', artifact_family: 'cycle_comparator_03_05', contract_source: 'dashboard/public/cycle_comparator_03_05.json', owning_system: 'RIL', render_gate_dependency: ['cycle_comparator_03_05.json'], freshness_dependency: ['cycle_comparator_03_05.json'], provenance_requirements: ['disagreement rows must link to governed comparison records'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'policy_regression', title: 'Policy regression surface', artifact_family: 'cycle_comparator_03_05', contract_source: 'dashboard/public/cycle_comparator_03_05.json', owning_system: 'PRG', render_gate_dependency: ['cycle_comparator_03_05.json'], freshness_dependency: ['cycle_comparator_03_05.json'], provenance_requirements: ['policy drift and outcome deltas must remain read-only'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'capability_readiness', title: 'Capability readiness surface', artifact_family: 'readiness_to_expand_validator', contract_source: 'dashboard/public/readiness_to_expand_validator.json', owning_system: 'SEL', render_gate_dependency: ['readiness_to_expand_validator.json'], freshness_dependency: ['readiness_to_expand_validator.json'], provenance_requirements: ['readiness state requires evidence_basis and confidence fields'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: true },
  { panel_id: 'route_efficiency', title: 'Route efficiency surface', artifact_family: 'operator_trust_closeout_artifact', contract_source: 'dashboard/public/operator_trust_closeout_artifact.json', owning_system: 'FRE', render_gate_dependency: ['operator_trust_closeout_artifact.json'], freshness_dependency: ['operator_trust_closeout_artifact.json'], provenance_requirements: ['quality/cost/latency rows require explicit uncertainty'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'failure_derived_eval', title: 'Failure-derived eval surface', artifact_family: 'next_action_outcome_record', contract_source: 'dashboard/public/next_action_outcome_record.json', owning_system: 'PQX', render_gate_dependency: ['next_action_outcome_record.json'], freshness_dependency: ['next_action_outcome_record.json'], provenance_requirements: ['failure-to-eval trace rows must remain artifact-backed'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'correction_patterns', title: 'Correction pattern surface', artifact_family: 'operator_override_capture', contract_source: 'dashboard/public/rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', owning_system: 'TLC', render_gate_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'], freshness_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'], provenance_requirements: ['pattern recurrence and absorption flags must be traceable'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'review_outcomes', title: 'Review outcome surface', artifact_family: 'recommendation_review_surface', contract_source: 'dashboard/public/recommendation_review_surface.json', owning_system: 'RIL', render_gate_dependency: ['recommendation_review_surface.json'], freshness_dependency: ['recommendation_review_surface.json'], provenance_requirements: ['review disposition rows link to queue outcome identifiers'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: true },
  { panel_id: 'escalation_triggers', title: 'Escalation trigger surface', artifact_family: 'hard_gate_status_record + publication_attempt_record', contract_source: 'dashboard/public/hard_gate_status_record.json', owning_system: 'SEL', render_gate_dependency: ['hard_gate_status_record.json', 'publication_attempt_record.json'], freshness_dependency: ['hard_gate_status_record.json'], provenance_requirements: ['threshold proximity and actual decision must be shown as separate fields'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: true },
  { panel_id: 'cross_run_intelligence', title: 'Cross-run intelligence view', artifact_family: 'cycle_comparator_03_05', contract_source: 'dashboard/public/cycle_comparator_03_05.json', owning_system: 'CDE', render_gate_dependency: ['cycle_comparator_03_05.json'], freshness_dependency: ['cycle_comparator_03_05.json'], provenance_requirements: ['cross-run dimensions derive only from comparison artifacts'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'high_risk_claim_board', title: 'High-risk claim board', artifact_family: 'readiness_to_expand_validator', contract_source: 'dashboard/public/readiness_to_expand_validator.json', owning_system: 'PRG', render_gate_dependency: ['readiness_to_expand_validator.json'], freshness_dependency: ['readiness_to_expand_validator.json'], provenance_requirements: ['claim rows limited to certification-relevant high-materiality evidence refs'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: true },
  { panel_id: 'governed_exports', title: 'Governed export surface', artifact_family: 'operator_surface_snapshot_export + dashboard publication gates', contract_source: 'dashboard/public/operator_surface_snapshot_export.json', owning_system: 'CDE', render_gate_dependency: ['operator_surface_snapshot_export.json', 'dashboard_publication_manifest.json'], freshness_dependency: ['operator_surface_snapshot_export.json', 'dashboard_freshness_status.json'], provenance_requirements: ['projection-only export status and verification state must be explicit'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: true }
,

  { panel_id: 'trust_posture_artifact_browser', title: 'Trust posture artifact browser', artifact_family: 'operator_trust_closeout_artifact', contract_source: 'dashboard/public/operator_trust_closeout_artifact.json', owning_system: 'SEL', render_gate_dependency: ['operator_trust_closeout_artifact.json'], freshness_dependency: ['operator_trust_closeout_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'trust_posture_diff', title: 'Trust posture diff view', artifact_family: 'operator_trust_closeout_artifact', contract_source: 'dashboard/public/operator_trust_closeout_artifact.json', owning_system: 'SEL', render_gate_dependency: ['operator_trust_closeout_artifact.json'], freshness_dependency: ['operator_trust_closeout_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'capability_readiness_timeline', title: 'Capability readiness timeline', artifact_family: 'readiness_to_expand_validator', contract_source: 'dashboard/public/readiness_to_expand_validator.json', owning_system: 'SEL', render_gate_dependency: ['readiness_to_expand_validator.json'], freshness_dependency: ['readiness_to_expand_validator.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'capability_expansion_blockers', title: 'Capability expansion blockers', artifact_family: 'readiness_to_expand_validator', contract_source: 'dashboard/public/readiness_to_expand_validator.json', owning_system: 'SEL', render_gate_dependency: ['readiness_to_expand_validator.json'], freshness_dependency: ['readiness_to_expand_validator.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'improvement_recommendation', title: 'Improvement recommendation surface', artifact_family: 'next_action_recommendation_record', contract_source: 'dashboard/public/next_action_recommendation_record.json', owning_system: 'PRG', render_gate_dependency: ['next_action_recommendation_record.json'], freshness_dependency: ['next_action_recommendation_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'improvement_recommendation_outcomes', title: 'Improvement recommendation outcome view', artifact_family: 'next_action_outcome_record', contract_source: 'dashboard/public/next_action_outcome_record.json', owning_system: 'PRG', render_gate_dependency: ['next_action_outcome_record.json'], freshness_dependency: ['next_action_outcome_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'artifact_family_health', title: 'Artifact family health', artifact_family: 'dashboard_publication_sync_audit', contract_source: 'dashboard/public/dashboard_publication_sync_audit.json', owning_system: 'CDE', render_gate_dependency: ['dashboard_publication_sync_audit.json'], freshness_dependency: ['dashboard_publication_sync_audit.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'artifact_family_health_trend', title: 'Artifact family health trend', artifact_family: 'dashboard_publication_sync_audit', contract_source: 'dashboard/public/dashboard_publication_sync_audit.json', owning_system: 'CDE', render_gate_dependency: ['dashboard_publication_sync_audit.json'], freshness_dependency: ['dashboard_publication_sync_audit.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'evidence_coverage_density', title: 'Evidence coverage density', artifact_family: 'readiness_to_expand_validator', contract_source: 'dashboard/public/readiness_to_expand_validator.json', owning_system: 'CDE', render_gate_dependency: ['readiness_to_expand_validator.json'], freshness_dependency: ['readiness_to_expand_validator.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'evidence_sufficiency_change', title: 'Evidence sufficiency change', artifact_family: 'next_action_outcome_record', contract_source: 'dashboard/public/next_action_outcome_record.json', owning_system: 'CDE', render_gate_dependency: ['next_action_outcome_record.json'], freshness_dependency: ['next_action_outcome_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'judge_calibration', title: 'Judge calibration', artifact_family: 'confidence_calibration_artifact', contract_source: 'dashboard/public/confidence_calibration_artifact.json', owning_system: 'RIL', render_gate_dependency: ['confidence_calibration_artifact.json'], freshness_dependency: ['confidence_calibration_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'judge_drift', title: 'Judge drift', artifact_family: 'cycle_comparator_03_05', contract_source: 'dashboard/public/cycle_comparator_03_05.json', owning_system: 'RIL', render_gate_dependency: ['cycle_comparator_03_05.json'], freshness_dependency: ['cycle_comparator_03_05.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'human_correction_magnitude', title: 'Human correction magnitude', artifact_family: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture', contract_source: 'dashboard/public/rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', owning_system: 'TLC', render_gate_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'], freshness_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'correction_absorption', title: 'Correction absorption', artifact_family: 'next_action_outcome_record', contract_source: 'dashboard/public/next_action_outcome_record.json', owning_system: 'TLC', render_gate_dependency: ['next_action_outcome_record.json'], freshness_dependency: ['next_action_outcome_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'policy_deviation', title: 'Policy deviation', artifact_family: 'rq_next_24_01__umbrella_4__nx_20_governance_exception_register', contract_source: 'dashboard/public/rq_next_24_01__umbrella_4__nx_20_governance_exception_register.json', owning_system: 'PRG', render_gate_dependency: ['rq_next_24_01__umbrella_4__nx_20_governance_exception_register.json'], freshness_dependency: ['rq_next_24_01__umbrella_4__nx_20_governance_exception_register.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'policy_change_impact', title: 'Policy change impact', artifact_family: 'cycle_comparator_03_05', contract_source: 'dashboard/public/cycle_comparator_03_05.json', owning_system: 'PRG', render_gate_dependency: ['cycle_comparator_03_05.json'], freshness_dependency: ['cycle_comparator_03_05.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'route_distribution', title: 'Route distribution', artifact_family: 'operator_trust_closeout_artifact', contract_source: 'dashboard/public/operator_trust_closeout_artifact.json', owning_system: 'FRE', render_gate_dependency: ['operator_trust_closeout_artifact.json'], freshness_dependency: ['operator_trust_closeout_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'quality_vs_cost', title: 'Quality vs cost', artifact_family: 'operator_trust_closeout_artifact', contract_source: 'dashboard/public/operator_trust_closeout_artifact.json', owning_system: 'FRE', render_gate_dependency: ['operator_trust_closeout_artifact.json'], freshness_dependency: ['operator_trust_closeout_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'latency_vs_quality', title: 'Latency vs quality', artifact_family: 'operator_trust_closeout_artifact', contract_source: 'dashboard/public/operator_trust_closeout_artifact.json', owning_system: 'FRE', render_gate_dependency: ['operator_trust_closeout_artifact.json'], freshness_dependency: ['operator_trust_closeout_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'retry_validation_failure', title: 'Retry and validation failure', artifact_family: 'serial_bundle_validator_result', contract_source: 'dashboard/public/serial_bundle_validator_result.json', owning_system: 'CDE', render_gate_dependency: ['serial_bundle_validator_result.json'], freshness_dependency: ['serial_bundle_validator_result.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'prompt_version_impact', title: 'Prompt version impact', artifact_family: 'rq_next_24_01__umbrella_3__nx_14_decision_backtest_harness', contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_14_decision_backtest_harness.json', owning_system: 'TLC', render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_14_decision_backtest_harness.json'], freshness_dependency: ['rq_next_24_01__umbrella_3__nx_14_decision_backtest_harness.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'context_recipe_comparison', title: 'Context recipe comparison', artifact_family: 'rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator', contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json', owning_system: 'TLC', render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json'], freshness_dependency: ['rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'context_source_reliability', title: 'Context source reliability', artifact_family: 'rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary', contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary.json', owning_system: 'FRE', render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary.json'], freshness_dependency: ['rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'context_exclusion_rationale', title: 'Context exclusion rationale', artifact_family: 'rq_next_24_01__umbrella_2__nx_08_operator_action_admissibility_check', contract_source: 'dashboard/public/rq_next_24_01__umbrella_2__nx_08_operator_action_admissibility_check.json', owning_system: 'RIL', render_gate_dependency: ['rq_next_24_01__umbrella_2__nx_08_operator_action_admissibility_check.json'], freshness_dependency: ['rq_next_24_01__umbrella_2__nx_08_operator_action_admissibility_check.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'contradiction_type', title: 'Contradiction type', artifact_family: 'cycle_comparator_03_05', contract_source: 'dashboard/public/cycle_comparator_03_05.json', owning_system: 'FRE', render_gate_dependency: ['cycle_comparator_03_05.json'], freshness_dependency: ['cycle_comparator_03_05.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'cross_artifact_consistency', title: 'Cross-artifact consistency', artifact_family: 'dashboard_publication_sync_audit', contract_source: 'dashboard/public/dashboard_publication_sync_audit.json', owning_system: 'CDE', render_gate_dependency: ['dashboard_publication_sync_audit.json'], freshness_dependency: ['dashboard_publication_sync_audit.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'schema_drift', title: 'Schema drift', artifact_family: 'dashboard_public_contract_coverage', contract_source: 'dashboard/public/dashboard_public_contract_coverage.json', owning_system: 'CDE', render_gate_dependency: ['dashboard_public_contract_coverage.json'], freshness_dependency: ['dashboard_public_contract_coverage.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'provenance_coverage', title: 'Provenance coverage', artifact_family: 'dashboard_publication_sync_audit', contract_source: 'dashboard/public/dashboard_publication_sync_audit.json', owning_system: 'CDE', render_gate_dependency: ['dashboard_publication_sync_audit.json'], freshness_dependency: ['dashboard_publication_sync_audit.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'lineage_coverage', title: 'Lineage coverage', artifact_family: 'serial_bundle_validator_result', contract_source: 'dashboard/public/serial_bundle_validator_result.json', owning_system: 'CDE', render_gate_dependency: ['serial_bundle_validator_result.json'], freshness_dependency: ['serial_bundle_validator_result.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'trace_integrity', title: 'Trace integrity', artifact_family: 'refresh_run_record', contract_source: 'dashboard/public/refresh_run_record.json', owning_system: 'CDE', render_gate_dependency: ['refresh_run_record.json'], freshness_dependency: ['refresh_run_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'openlineage_trace_correlation', title: 'Openlineage / trace correlation', artifact_family: 'refresh_run_record', contract_source: 'dashboard/public/refresh_run_record.json', owning_system: 'CDE', render_gate_dependency: ['refresh_run_record.json'], freshness_dependency: ['refresh_run_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'run_bundle_audit', title: 'Run bundle audit', artifact_family: 'serial_bundle_validator_result', contract_source: 'dashboard/public/serial_bundle_validator_result.json', owning_system: 'CDE', render_gate_dependency: ['serial_bundle_validator_result.json'], freshness_dependency: ['serial_bundle_validator_result.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'promotion_readiness', title: 'Promotion readiness', artifact_family: 'governed_promotion_discipline_gate', contract_source: 'dashboard/public/governed_promotion_discipline_gate.json', owning_system: 'SEL', render_gate_dependency: ['governed_promotion_discipline_gate.json'], freshness_dependency: ['governed_promotion_discipline_gate.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'promotion_failure', title: 'Promotion failure', artifact_family: 'governed_promotion_discipline_gate', contract_source: 'dashboard/public/governed_promotion_discipline_gate.json', owning_system: 'SEL', render_gate_dependency: ['governed_promotion_discipline_gate.json'], freshness_dependency: ['governed_promotion_discipline_gate.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'certification_failure', title: 'Certification failure', artifact_family: 'serial_bundle_validator_result', contract_source: 'dashboard/public/serial_bundle_validator_result.json', owning_system: 'SEL', render_gate_dependency: ['serial_bundle_validator_result.json'], freshness_dependency: ['serial_bundle_validator_result.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'replay_mismatch_root_cause', title: 'Replay mismatch root cause', artifact_family: 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack', contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', owning_system: 'PQX', render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json'], freshness_dependency: ['rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'replay_stability', title: 'Replay stability', artifact_family: 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack', contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', owning_system: 'PQX', render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json'], freshness_dependency: ['rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'non_determinism_hotspot', title: 'Non-determinism hotspot', artifact_family: 'drift_trend_continuity_artifact', contract_source: 'dashboard/public/drift_trend_continuity_artifact.json', owning_system: 'PQX', render_gate_dependency: ['drift_trend_continuity_artifact.json'], freshness_dependency: ['drift_trend_continuity_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'error_budget_burn', title: 'Error budget burn', artifact_family: 'error_budget_enforcement_outcome', contract_source: 'dashboard/public/error_budget_enforcement_outcome.json', owning_system: 'FRE', render_gate_dependency: ['error_budget_enforcement_outcome.json'], freshness_dependency: ['error_budget_enforcement_outcome.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'budget_breach_history', title: 'Budget breach history', artifact_family: 'error_budget_enforcement_outcome', contract_source: 'dashboard/public/error_budget_enforcement_outcome.json', owning_system: 'FRE', render_gate_dependency: ['error_budget_enforcement_outcome.json'], freshness_dependency: ['error_budget_enforcement_outcome.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'incident_correlation', title: 'Incident correlation', artifact_family: 'refresh_run_record', contract_source: 'dashboard/public/refresh_run_record.json', owning_system: 'FRE', render_gate_dependency: ['refresh_run_record.json'], freshness_dependency: ['refresh_run_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'alert_quality', title: 'Alert quality', artifact_family: 'hard_gate_status_record', contract_source: 'dashboard/public/hard_gate_status_record.json', owning_system: 'FRE', render_gate_dependency: ['hard_gate_status_record.json'], freshness_dependency: ['hard_gate_status_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'review_queue_load', title: 'Review queue load', artifact_family: 'recommendation_review_surface', contract_source: 'dashboard/public/recommendation_review_surface.json', owning_system: 'RIL', render_gate_dependency: ['recommendation_review_surface.json'], freshness_dependency: ['recommendation_review_surface.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'review_queue_routing_quality', title: 'Review queue routing quality', artifact_family: 'recommendation_review_surface', contract_source: 'dashboard/public/recommendation_review_surface.json', owning_system: 'RIL', render_gate_dependency: ['recommendation_review_surface.json'], freshness_dependency: ['recommendation_review_surface.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'review_debt', title: 'Review debt', artifact_family: 'recommendation_review_surface', contract_source: 'dashboard/public/recommendation_review_surface.json', owning_system: 'RIL', render_gate_dependency: ['recommendation_review_surface.json'], freshness_dependency: ['recommendation_review_surface.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'review_to_eval_closure', title: 'Review-to-eval closure', artifact_family: 'next_action_outcome_record', contract_source: 'dashboard/public/next_action_outcome_record.json', owning_system: 'RIL', render_gate_dependency: ['next_action_outcome_record.json'], freshness_dependency: ['next_action_outcome_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'hitl_override_quality', title: 'HITL override quality', artifact_family: 'rq_next_24_01__umbrella_1__nx_05_operator_override_capture', contract_source: 'dashboard/public/rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json', owning_system: 'SEL', render_gate_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'], freshness_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'human_review_reason', title: 'Human review reason', artifact_family: 'recommendation_review_surface', contract_source: 'dashboard/public/recommendation_review_surface.json', owning_system: 'RIL', render_gate_dependency: ['recommendation_review_surface.json'], freshness_dependency: ['recommendation_review_surface.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'decision_log_integrity', title: 'Decision-log integrity', artifact_family: 'judgment_application_artifact', contract_source: 'dashboard/public/judgment_application_artifact.json', owning_system: 'RIL', render_gate_dependency: ['judgment_application_artifact.json'], freshness_dependency: ['judgment_application_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'decision_alternative', title: 'Decision alternative', artifact_family: 'judgment_application_artifact', contract_source: 'dashboard/public/judgment_application_artifact.json', owning_system: 'RIL', render_gate_dependency: ['judgment_application_artifact.json'], freshness_dependency: ['judgment_application_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'decision_fragility', title: 'Decision fragility', artifact_family: 'rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator', contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json', owning_system: 'RIL', render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json'], freshness_dependency: ['rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'counterfactual_study_index', title: 'Counterfactual study index', artifact_family: 'rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator', contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json', owning_system: 'RIL', render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json'], freshness_dependency: ['rq_next_24_01__umbrella_3__nx_15_counterfactual_recommendation_evaluator.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'route_canary', title: 'Route canary', artifact_family: 'rq_next_24_01__umbrella_4__nx_23_controlled_expansion_canary_gate', contract_source: 'dashboard/public/rq_next_24_01__umbrella_4__nx_23_controlled_expansion_canary_gate.json', owning_system: 'FRE', render_gate_dependency: ['rq_next_24_01__umbrella_4__nx_23_controlled_expansion_canary_gate.json'], freshness_dependency: ['rq_next_24_01__umbrella_4__nx_23_controlled_expansion_canary_gate.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'model_tournament', title: 'Model tournament', artifact_family: 'rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary', contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary.json', owning_system: 'FRE', render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary.json'], freshness_dependency: ['rq_next_24_01__umbrella_3__nx_18_simulation_outcome_summary.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'slice_severity', title: 'Slice severity', artifact_family: 'readiness_to_expand_validator', contract_source: 'dashboard/public/readiness_to_expand_validator.json', owning_system: 'PRG', render_gate_dependency: ['readiness_to_expand_validator.json'], freshness_dependency: ['readiness_to_expand_validator.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'missing_eval_slice', title: 'Missing eval slice', artifact_family: 'next_action_outcome_record', contract_source: 'dashboard/public/next_action_outcome_record.json', owning_system: 'PRG', render_gate_dependency: ['next_action_outcome_record.json'], freshness_dependency: ['next_action_outcome_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'blocking_bottleneck', title: 'Blocking bottleneck', artifact_family: 'current_bottleneck_record', contract_source: 'dashboard/public/current_bottleneck_record.json', owning_system: 'PRG', render_gate_dependency: ['current_bottleneck_record.json'], freshness_dependency: ['current_bottleneck_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'roadmap_feed', title: 'Roadmap feed', artifact_family: 'canonical_roadmap_state_artifact', contract_source: 'dashboard/public/canonical_roadmap_state_artifact.json', owning_system: 'PRG', render_gate_dependency: ['canonical_roadmap_state_artifact.json'], freshness_dependency: ['canonical_roadmap_state_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'control_vs_roadmap_split', title: 'Control vs roadmap split', artifact_family: 'canonical_roadmap_state_artifact', contract_source: 'dashboard/public/canonical_roadmap_state_artifact.json', owning_system: 'PRG', render_gate_dependency: ['canonical_roadmap_state_artifact.json'], freshness_dependency: ['canonical_roadmap_state_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'human_review_consumption', title: 'Human review consumption', artifact_family: 'recommendation_review_surface', contract_source: 'dashboard/public/recommendation_review_surface.json', owning_system: 'RIL', render_gate_dependency: ['recommendation_review_surface.json'], freshness_dependency: ['recommendation_review_surface.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'quality_sli', title: 'Quality SLI', artifact_family: 'dashboard_freshness_status', contract_source: 'dashboard/public/dashboard_freshness_status.json', owning_system: 'CDE', render_gate_dependency: ['dashboard_freshness_status.json'], freshness_dependency: ['dashboard_freshness_status.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'reliability_sli', title: 'Reliability SLI', artifact_family: 'refresh_run_record', contract_source: 'dashboard/public/refresh_run_record.json', owning_system: 'CDE', render_gate_dependency: ['refresh_run_record.json'], freshness_dependency: ['refresh_run_record.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'capacity_cost_sli', title: 'Capacity / cost SLI', artifact_family: 'error_budget_enforcement_outcome', contract_source: 'dashboard/public/error_budget_enforcement_outcome.json', owning_system: 'CDE', render_gate_dependency: ['error_budget_enforcement_outcome.json'], freshness_dependency: ['error_budget_enforcement_outcome.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'time_to_insight', title: 'Time-to-insight', artifact_family: 'operator_trust_closeout_artifact', contract_source: 'dashboard/public/operator_trust_closeout_artifact.json', owning_system: 'TLC', render_gate_dependency: ['operator_trust_closeout_artifact.json'], freshness_dependency: ['operator_trust_closeout_artifact.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'link_integrity', title: 'Link integrity', artifact_family: 'dashboard_publication_manifest', contract_source: 'dashboard/public/dashboard_publication_manifest.json', owning_system: 'CDE', render_gate_dependency: ['dashboard_publication_manifest.json'], freshness_dependency: ['dashboard_publication_manifest.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'dashboard_self_health', title: 'Dashboard self-health', artifact_family: 'dashboard_public_contract_coverage', contract_source: 'dashboard/public/dashboard_public_contract_coverage.json', owning_system: 'CDE', render_gate_dependency: ['dashboard_public_contract_coverage.json'], freshness_dependency: ['dashboard_public_contract_coverage.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'operator_session_path', title: 'Operator session path', artifact_family: 'operator_surface_snapshot_export', contract_source: 'dashboard/public/operator_surface_snapshot_export.json', owning_system: 'TLC', render_gate_dependency: ['operator_surface_snapshot_export.json'], freshness_dependency: ['operator_surface_snapshot_export.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'cognitive_load', title: 'Cognitive load', artifact_family: 'operator_surface_snapshot_export', contract_source: 'dashboard/public/operator_surface_snapshot_export.json', owning_system: 'TLC', render_gate_dependency: ['operator_surface_snapshot_export.json'], freshness_dependency: ['operator_surface_snapshot_export.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'panel_materiality_ranking', title: 'Panel materiality ranking', artifact_family: 'dashboard_publication_sync_audit', contract_source: 'dashboard/public/dashboard_publication_sync_audit.json', owning_system: 'PRG', render_gate_dependency: ['dashboard_publication_sync_audit.json'], freshness_dependency: ['dashboard_publication_sync_audit.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'panel_retirement_candidate', title: 'Panel retirement candidate', artifact_family: 'dashboard_public_contract_coverage', contract_source: 'dashboard/public/dashboard_public_contract_coverage.json', owning_system: 'PRG', render_gate_dependency: ['dashboard_public_contract_coverage.json'], freshness_dependency: ['dashboard_public_contract_coverage.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
  { panel_id: 'certification_gate_reinforcement', title: 'Certification gate reinforcement', artifact_family: 'governed_promotion_discipline_gate', contract_source: 'dashboard/public/governed_promotion_discipline_gate.json', owning_system: 'SEL', render_gate_dependency: ['governed_promotion_discipline_gate.json'], freshness_dependency: ['governed_promotion_discipline_gate.json'], provenance_requirements: ['field-level traceability and explicit uncertainty labels'], blocked_state_behavior: 'render_blocked_diagnostic', allowed_statuses: ['renderable', 'blocked'], certification_relevant: true, high_risk: true, mobile_critical: false },
]