export type SurfaceStatus = 'renderable' | 'blocked' | 'warning'

export type DashboardSurfaceContract = {
  panel_id: string
  title: string
  artifact_family: string
  contract_source: string
  owning_system: 'RIL' | 'CDE' | 'TLC' | 'PQX' | 'FRE' | 'SEL' | 'PRG'
  render_gate_dependency: string[]
  freshness_dependency: string[]
  provenance_requirements: string[]
  blocked_state_behavior: 'hide_panel' | 'render_blocked_diagnostic'
  allowed_statuses: SurfaceStatus[]
  certification_relevant: boolean
  high_risk: boolean
  mobile_critical: boolean
}

export const DASHBOARD_SURFACE_CONTRACT_REGISTRY: DashboardSurfaceContract[] = [
  {
    panel_id: 'trust_posture',
    title: 'Trust posture',
    artifact_family: 'dashboard_freshness_status + dashboard_publication_sync_audit',
    contract_source: 'dashboard/public/dashboard_freshness_status.json',
    owning_system: 'SEL',
    render_gate_dependency: ['dashboard_freshness_status.json', 'dashboard_publication_manifest.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['field-level trace for freshness, validation, provenance, replay, renderability'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'causal_chain',
    title: 'Causal chain',
    artifact_family: 'publication_attempt_record + judgment_application_artifact + hard_gate_status_record + serial_bundle_validator_result',
    contract_source: 'dashboard/public/publication_attempt_record.json',
    owning_system: 'TLC',
    render_gate_dependency: ['publication_attempt_record.json', 'judgment_application_artifact.json', 'hard_gate_status_record.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['publication_attempt_record.json', 'serial_bundle_validator_result.json'],
    provenance_requirements: ['artifact-linked edge trace for eval → judgment → control → outcome'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'decision_trace',
    title: 'Decision trace',
    artifact_family: 'publication_attempt_record + judgment_application_artifact + hard_gate_status_record',
    contract_source: 'dashboard/public/judgment_application_artifact.json',
    owning_system: 'RIL',
    render_gate_dependency: ['publication_attempt_record.json', 'judgment_application_artifact.json', 'hard_gate_status_record.json'],
    freshness_dependency: ['publication_attempt_record.json'],
    provenance_requirements: ['decision reasons must be field-traceable to artifacts'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'multi_artifact_correlation',
    title: 'Multi-artifact correlation',
    artifact_family: 'current_bottleneck_record + current_run_state_record + hard_gate_status_record + judgment_application_artifact + serial_bundle_validator_result',
    contract_source: 'dashboard/public/current_bottleneck_record.json',
    owning_system: 'PRG',
    render_gate_dependency: ['current_bottleneck_record.json', 'current_run_state_record.json', 'hard_gate_status_record.json', 'judgment_application_artifact.json'],
    freshness_dependency: ['current_run_state_record.json', 'serial_bundle_validator_result.json'],
    provenance_requirements: ['correlation rows must preserve source artifact and consumed fields'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: false,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'evidence_strength',
    title: 'Evidence strength',
    artifact_family: 'dashboard_publication_sync_audit + dashboard_freshness_status + serial_bundle_validator_result + dashboard_public_contract_coverage',
    contract_source: 'dashboard/public/dashboard_publication_sync_audit.json',
    owning_system: 'CDE',
    render_gate_dependency: ['dashboard_publication_sync_audit.json', 'dashboard_freshness_status.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['dimension-level rows for provenance depth/agreement/freshness/validation/replay'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'control_decisions',
    title: 'Control decisions',
    artifact_family: 'publication_attempt_record + hard_gate_status_record',
    contract_source: 'dashboard/public/publication_attempt_record.json',
    owning_system: 'SEL',
    render_gate_dependency: ['publication_attempt_record.json', 'hard_gate_status_record.json'],
    freshness_dependency: ['publication_attempt_record.json'],
    provenance_requirements: ['decision code and reason_codes trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'judgment_records',
    title: 'Judgment records',
    artifact_family: 'judgment_application_artifact',
    contract_source: 'dashboard/public/judgment_application_artifact.json',
    owning_system: 'RIL',
    render_gate_dependency: ['judgment_application_artifact.json'],
    freshness_dependency: ['judgment_application_artifact.json'],
    provenance_requirements: ['judgment_ids and decision_id trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'override_lifecycle',
    title: 'Override lifecycle',
    artifact_family: 'operator_override_capture',
    contract_source: 'dashboard/public/rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json',
    owning_system: 'SEL',
    render_gate_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'],
    freshness_dependency: ['rq_next_24_01__umbrella_1__nx_05_operator_override_capture.json'],
    provenance_requirements: ['override_id and reason trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'replay_certification',
    title: 'Replay and certification',
    artifact_family: 'recommendation_replay_pack + serial_bundle_validator_result + governed_promotion_discipline_gate',
    contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json',
    owning_system: 'CDE',
    render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['serial_bundle_validator_result.json'],
    provenance_requirements: ['scenario ids and pass/fail trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'weighted_coverage',
    title: 'Weighted coverage',
    artifact_family: 'dashboard_public_contract_coverage + dashboard_publication_manifest',
    contract_source: 'dashboard/public/dashboard_public_contract_coverage.json',
    owning_system: 'PRG',
    render_gate_dependency: ['dashboard_public_contract_coverage.json', 'dashboard_publication_manifest.json'],
    freshness_dependency: ['dashboard_public_contract_coverage.json'],
    provenance_requirements: ['covered_artifacts and required_files trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked', 'warning'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'trend_control_charts',
    title: 'Trend control charts',
    artifact_family: 'dashboard_freshness_status + refresh_run_record + publication_attempt_record',
    contract_source: 'dashboard/public/dashboard_freshness_status.json',
    owning_system: 'TLC',
    render_gate_dependency: ['dashboard_freshness_status.json', 'refresh_run_record.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['threshold + observed values trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: false,
    high_risk: false,
    mobile_critical: false
  },
  {
    panel_id: 'reconciliation',
    title: 'High-risk reconciliation',
    artifact_family: 'dashboard_freshness_status + publication_attempt_record',
    contract_source: 'dashboard/public/publication_attempt_record.json',
    owning_system: 'SEL',
    render_gate_dependency: ['dashboard_freshness_status.json', 'publication_attempt_record.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['dual-source verdict disagreement trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'postmortem_outage',
    title: 'Postmortem and outage',
    artifact_family: 'refresh_run_record + publication_attempt_record + drift_trend_continuity_artifact',
    contract_source: 'dashboard/public/refresh_run_record.json',
    owning_system: 'FRE',
    render_gate_dependency: ['refresh_run_record.json', 'publication_attempt_record.json'],
    freshness_dependency: ['refresh_run_record.json'],
    provenance_requirements: ['failure class and trace link'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: false,
    high_risk: false,
    mobile_critical: false
  },
  {
    panel_id: 'tamper_evident_ledger',
    title: 'Tamper-evident publication ledger',
    artifact_family: 'dashboard_publication_sync_audit + serial_bundle_validator_result',
    contract_source: 'dashboard/public/dashboard_publication_sync_audit.json',
    owning_system: 'CDE',
    render_gate_dependency: ['dashboard_publication_sync_audit.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['dashboard_publication_sync_audit.json'],
    provenance_requirements: ['record-level verification flags trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'maintain_drift',
    title: 'Maintain and drift',
    artifact_family: 'dashboard_publication_manifest + dashboard_public_contract_coverage + operator_override_capture',
    contract_source: 'dashboard/public/dashboard_publication_manifest.json',
    owning_system: 'PRG',
    render_gate_dependency: ['dashboard_publication_manifest.json', 'dashboard_public_contract_coverage.json'],
    freshness_dependency: ['dashboard_publication_manifest.json'],
    provenance_requirements: ['dead panel and mismatch signals trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked', 'warning'],
    certification_relevant: false,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'scenario_simulator',
    title: 'Governed scenario simulator',
    artifact_family: 'governed fixture bundle',
    contract_source: 'dashboard/public/rq_next_24_01__umbrella_3__nx_17_failure_hotspot_simulation_pack.json',
    owning_system: 'PQX',
    render_gate_dependency: ['rq_next_24_01__umbrella_3__nx_17_failure_hotspot_simulation_pack.json'],
    freshness_dependency: ['rq_next_24_01__umbrella_3__nx_17_failure_hotspot_simulation_pack.json'],
    provenance_requirements: ['fixture scenario identifiers trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: false,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'mobile_semantics',
    title: 'Mobile operator semantics',
    artifact_family: 'read-model diagnostics',
    contract_source: 'dashboard/lib/read_model/dashboard_read_model_compiler.ts',
    owning_system: 'TLC',
    render_gate_dependency: ['dashboard_freshness_status.json', 'publication_attempt_record.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['blocked-state and high-risk cues trace'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'policy_visibility',
    title: 'Policy visibility',
    artifact_family: 'hard_gate_status_record + governed_promotion_discipline_gate',
    contract_source: 'dashboard/public/hard_gate_status_record.json',
    owning_system: 'SEL',
    render_gate_dependency: ['hard_gate_status_record.json', 'governed_promotion_discipline_gate.json'],
    freshness_dependency: ['hard_gate_status_record.json'],
    provenance_requirements: ['policy threshold and enforcement rule fields rendered read-only'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'audit_trail',
    title: 'Audit trail',
    artifact_family: 'publication_attempt_record + judgment_application_artifact + refresh_run_record + serial_bundle_validator_result',
    contract_source: 'dashboard/public/publication_attempt_record.json',
    owning_system: 'CDE',
    render_gate_dependency: ['publication_attempt_record.json', 'judgment_application_artifact.json', 'refresh_run_record.json', 'serial_bundle_validator_result.json'],
    freshness_dependency: ['publication_attempt_record.json', 'refresh_run_record.json'],
    provenance_requirements: ['decision history, transitions, and trace lineage are artifact-linked'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: false
  },
  {
    panel_id: 'action_surface',
    title: 'Governed non-decision actions',
    artifact_family: 'refresh_run_record + recommendation_replay_pack + recommendation_review_surface',
    contract_source: 'dashboard/public/refresh_run_record.json',
    owning_system: 'TLC',
    render_gate_dependency: ['refresh_run_record.json', 'rq_next_24_01__umbrella_3__nx_13_recommendation_replay_pack.json', 'recommendation_review_surface.json'],
    freshness_dependency: ['refresh_run_record.json'],
    provenance_requirements: ['action list must be refresh/replay/review-handoff only and artifact traceable'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'review_queue_surface',
    title: 'Review queue surface',
    artifact_family: 'recommendation_review_surface + hard_gate_status_record',
    contract_source: 'dashboard/public/recommendation_review_surface.json',
    owning_system: 'RIL',
    render_gate_dependency: ['recommendation_review_surface.json', 'hard_gate_status_record.json'],
    freshness_dependency: ['recommendation_review_surface.json'],
    provenance_requirements: ['pending review records and HITL checkpoints are artifact-backed'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  },
  {
    panel_id: 'misinterpretation_guard',
    title: 'Misinterpretation guard',
    artifact_family: 'dashboard_freshness_status + serial_bundle_validator_result + publication_attempt_record',
    contract_source: 'dashboard/public/dashboard_freshness_status.json',
    owning_system: 'FRE',
    render_gate_dependency: ['dashboard_freshness_status.json', 'serial_bundle_validator_result.json', 'publication_attempt_record.json'],
    freshness_dependency: ['dashboard_freshness_status.json'],
    provenance_requirements: ['low-evidence and disagreement states force explicit uncertainty labels'],
    blocked_state_behavior: 'render_blocked_diagnostic',
    allowed_statuses: ['renderable', 'blocked'],
    certification_relevant: true,
    high_risk: true,
    mobile_critical: true
  }
]
